# Laboratorio Matematico Orfini Foligno - Project Context

## Project Overview

**Laboratorio Matematico Orfini Foligno** is an interactive digital hub designed for the "Istituto Professionale Orfini" in Foligno. It provides a suite of educational web applications ("lessons") for Mathematics, Physics, and Civic Education. The platform focuses on gamification, 3D visualization, and interactive learning (PBL - Project Based Learning).

The project is a **static web application** with a lightweight Python-based build system to manage content indexing.

## Tech Stack

*   **Core:** HTML5, CSS3, Modern JavaScript (ES6+).
*   **Styling:** Custom CSS based on **Material Design 3** principles (Variables for Dynamic Color & Dark/Light Mode).
*   **Graphics:** [Three.js](https://threejs.org/) (via CDN) for 3D visualizations (e.g., the "Word Cloud" navigation in the homepage).
*   **Build Tool:** Python 3 (`build.py`).
*   **Data Source:** `database.js` (JSON-like structure generated by the build script).

## Directory Structure

*   `root`: Contains the main dashboard and configuration.
    *   `index.html`: The main entry point (Dashboard). Dynamically renders lesson cards and 3D navigation based on `database.js`.
    *   `build.py`: Automation script to index lessons.
    *   `database.js`: **[GENERATED]** Contains the registry of all lessons. **Do not edit manually.**
    *   `competenze.js`: Reference file defining the Educational Competencies (EU, Math, Civic) used for tagging.
*   `lezioni/`: Directory containing the actual educational content.
    *   Each file (e.g., `albero_pitagorico.html`, `fractions_lab.html`) is a standalone web application.

## Workflow & Development

### 1. Adding a New Lesson
To add a new interactive lesson or game:
1.  Create a new HTML file in the `lezioni/` directory.
2.  **Crucial:** You **MUST** include specific metadata in the `<head>` for the indexer to pick it up correctly:
    ```html
    <head>
        <title>Lesson Title</title>
        <meta name="description" content="Short description of the activity.">
        <meta name="keywords" content="Matematica, Algebra, Tag1, Tag2">
        <meta name="date" content="YYYY-MM-DD">
        <!-- ... other styles and scripts ... -->
    </head>
    ```
3.  Use tags that align with `competenze.js` where possible (e.g., `Mat:Calcolo`, `EU:STEM`).

### 2. Building the Project
After adding or modifying lessons in `lezioni/`, you must update the central database.
Run the build script from the project root:

```bash
python3 build.py
```

**What it does:**
*   Scans `lezioni/*.html`.
*   Extracts metadata (Title, Description, Keywords, Date).
*   Infers an icon based on tags.
*   Generates/Overwrites `database.js`.

### 3. Running Locally
Since this is a static site using ES modules and CORS (for Three.js textures/imports), it is best run via a local server:

```bash
# Python 3
python3 -m http.server 8000
```
Then access `http://localhost:8000`.

## Code Conventions

*   **Formatting:** Standard HTML/CSS/JS formatting.
*   **Theme:** Respect the CSS variables for colors to support the global Dark/Light mode switcher.
    *   Use `var(--md-sys-color-background)`, `var(--md-sys-color-primary)`, etc.
*   **Independence:** Each lesson in `lezioni/` should be relatively self-contained, though they may share assets if a central `assets/` folder is created (currently not present in the root list).
*   **Libraries:** Prefer CDN links (like `jsdelivr` for Three.js) for easy deployment on GitHub Pages without a complex bundler.

## Key Files Reference

| File | Purpose |
| :--- | :--- |
| `build.py` | Indexes content. Run this after content changes. |
| `database.js` | Read-only data file loaded by `index.html`. |
| `competenze.js` | Dictionary of educational tags. Use for reference. |
| `index.html` | Main dashboard/portfolio. |
