/* 
   ⚠️ GENERATO AUTOMATICAMENTE DA build.py 
   Data: 2026-08-26 11:41:11
*/

const db = [
    {
        "title": "Studio Plotter CNC",
        "excerpt": "Generatore ed elaboratore G-Code avanzato per pen plotter e CNC, con algoritmi generativi e simulatore 3D.",
        "tags": [
            "G-CODE",
            "IND_C2:CODING E SIMULAZIONI STEM",
            "3 MEC",
            "STAMPA 3D",
            "5 EL",
            "CNC",
            "L-SYSTEM",
            "STUDIO PLOTTER CNC",
            "IND_C1:MODELLAZIONE ALGORITMICA E PARAMETRICA",
            "IND_C3:FABBRICAZIONE DIGITALE 3D",
            "MODELLAZIONE PARAMETRICA",
            "FRATTALI",
            "MATEMATICA",
            "MAT_C4:MODELLI GEOMETRICI E SPAZIALI",
            "PEN PLOTTER",
            "ATTRATTORI",
            "CIT_4:COMPETENZA DIGITALE",
            "MANIFATTURA DIGITALE",
            "4 EL",
            "ALGORITMI",
            "SLICING",
            "ARTE GENERATIVA",
            "TRASVERSALE",
            "CIT_7:SPIRITO DI INIZIATIVA"
        ],
        "date": "2026-08-27",
        "url": "content/apps/pen_plotter__23v2_8K.html",
        "type": "app",
        "icon": "📈",
        "game_type": "sim"
    },
    {
        "title": "Teoria dei giochi e valutazione consapevole",
        "excerpt": "Simulazione interattiva del Dilemma del Prigioniero ed Equilibrio di Nash. Laboratorio per esplorare la cooperazione e le scelte strategiche nel contesto del voto scolastico.",
        "tags": [
            "CITTADINANZA",
            "MAT:MODELLIZZAZIONE",
            "CIT_6:COMPETENZE SOCIALI E CIVICHE",
            "MAT:DATI",
            "TEORIA DEI GIOCHI",
            "EU:CITTADINANZA",
            "CIV:COSTITUZIONE",
            "MAT_C3:ANALIZZARE DATI E INTERPRETARE INFORMAZIONI C...",
            "MATEMATICA",
            "EQUILIBRIO DI NASH",
            "4 EL",
            "ED. CIVICA"
        ],
        "date": "2026-08-26",
        "url": "content/apps/voto_cosapevole.2.5.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/voto_cosapevole.2.5.jpg"
    },
    {
        "title": "PixelGrid",
        "excerpt": "Applicazione di Game Theory all'analisi delle radici nelle equazioni di secondo grado, esplorando l'ottimizzazione e le strategie dominanti.",
        "tags": [
            "ALGEBRA",
            "QUADRATICHE",
            "PRODOTTI NOTEVOLI",
            "FATTORIZZAZIONE",
            "SCOMPOSIZIONE",
            "MODELLIZZAZIONE",
            "3 MEC",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "PARABOLA",
            "G",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "4 EL",
            "EQUAZIONI DI SECONDO GRADO",
            "ITA",
            "POLINOMI"
        ],
        "date": "2026-08-26",
        "url": "content/apps/eq_2_gr_teoria_giochi_01.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/eq_2_gr_teoria_giochi_01.jpg"
    },
    {
        "title": "Challenge: Scomposizione di Polinomi (PRO)",
        "excerpt": "Versione PRO della sfida 3D sui polinomi: Ghost Target, X-Ray mode e variabili dinamiche.",
        "tags": [
            "ALGEBRA",
            "3D",
            "NERDAMER",
            "PRO",
            "1 EL",
            "SCOMPOSIZIONE",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "MATEMATICA",
            "POLINOMI"
        ],
        "date": "2026-05-27",
        "url": "content/apps/polinomi_challenge_v2_pro.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/polinomi_challenge_v2_pro.jpg"
    },
    {
        "title": "Experience Fibonacci",
        "excerpt": "Esplorazione interattiva della successione di Fibonacci, della spirale aurea e della fillotassi nei girasoli. Un'esperienza visiva per comprendere la convergenza del rapporto aureo e l'ottimizzazione geometrica in natura.",
        "tags": [
            "SEZIONE AUREA",
            "TRASVERSALE",
            "FILLOTASSI",
            "FIBONACCI",
            "NATURA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "SPIRALE AUREA",
            "PHI",
            "MATEMATICA",
            "GEOMETRIA",
            "P5.JS"
        ],
        "date": "2026-05-27",
        "url": "content/apps/fibonacci_anim.html",
        "type": "app",
        "icon": "📐",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/fibonacci_anim.jpg"
    },
    {
        "title": "Esploratore di Scale Logaritmiche",
        "excerpt": "Laboratorio interattivo sulle scale logaritmiche per esplorare la crescita esponenziale, le leggi di potenza e fenomeni fisici reali.",
        "tags": [
            "LABORATORIO",
            "LEGGE DI MOORE",
            "LEGGE DI KLEIBER",
            "SCALE LOGARITMICHE",
            "EPIDEMIOLOGIA",
            "ACUSTICA",
            "5 EL",
            "MATEMATICA",
            "CRESCITA ESPONENZIALE",
            "4 EL"
        ],
        "date": "2026-05-22",
        "url": "content/apps/scale_logaritmiche.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/scale_logaritmiche.jpg"
    },
    {
        "title": "Math Pool: Biliardo Cartesiano e retta",
        "excerpt": "Gamification e Laboratorio interattivo sulla Geometria Analitica. Gioca a biliardo nel piano cartesiano calcolando le equazioni delle retta e i punti di intersezione.",
        "tags": [
            "3 MEC",
            "BILIARDO",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "2 GP",
            "GAMIFICATION",
            "RETTA",
            "MATEMATICA",
            "GEOMETRIA ANALITICA",
            "PIANO CARTESIANO"
        ],
        "date": "2026-05-21",
        "url": "content/apps/math_pool_retta_pianocartesiano.html",
        "type": "app",
        "icon": "📐",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/math_pool_retta_pianocartesiano.jpg"
    },
    {
        "title": "Random Walk 3D | Hypercaos & Chromatic Memory",
        "excerpt": "Simulatore interattivo di passeggiate aleatorie in 3D. Esplora il caos deterministico e la geometria frattale (Koch, Hilbert, Peano) attraverso algoritmi generativi e morphing cromatico in tempo reale.",
        "tags": [
            "3D",
            "CAOS",
            "MAT_K3:GEOMETRIA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "SOFT_2:METACOGNIZIONE",
            "5 EL",
            "FRATTALI",
            "SOFT_2:PROBLEM SOLVING E PENSIERO CRITICO",
            "4 EL",
            "WEBGL",
            "IND_C2:CODING",
            "RANDOM WALK",
            "ALGORITMI"
        ],
        "date": "2026-05-16",
        "url": "content/apps/random_walk.html",
        "type": "app",
        "icon": "🌀",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/random_walk.jpg"
    },
    {
        "title": "Laboratorio Scomposizioni e Disequazioni di secondo grado | Parabola",
        "excerpt": "Ambiente di studio sinottico per lo studio delle disequazioni di secondo grado. Include scomposizione in fattori, metodo del delta, diagrammi dei segni e visualizzazione grafica della parabola in tempo reale.",
        "tags": [
            "SCOMPOSIZIONI",
            "ALGEBRA",
            "3 MEC",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "PARABOLA",
            "MAT_K1:ALGEBRA",
            "DISEQUAZIONI DI SECONDO GRADO",
            "DIDATTICA INCLUSIVA",
            "4 EL",
            "MAT_A3:EQUAZIONI E DISEQUAZIONI",
            "LABORATORIO METACOGNITIVO"
        ],
        "date": "2026-05-16",
        "url": "content/apps/parabola e disequazioni di secondo grado maggio 2026.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/parabola e disequazioni di secondo grado maggio 2026.jpg"
    },
    {
        "date": "2026-05-13",
        "description": "Esercitazione interattiva su GeoGebra per lo studio della retta passante per due punti. Esplorazione dinamica dei parametri.",
        "tags": [
            "LABORATORIO",
            "GEOGEBRA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "2 GP",
            "RETTA",
            "GEOMETRIA ANALITICA"
        ],
        "title": "Esercitazione GeoGebra: Retta per due punti",
        "url": "https://www.geogebra.org/m/mcfvzdfx",
        "excerpt": "Esercitazione interattiva su GeoGebra per lo studio della retta passante per due punti. Esplorazione dinamica dei parametri.",
        "type": "link",
        "icon": "🌐",
        "game_type": "sim"
    },
    {
        "title": "Palestra: Memory delle Scomposizioni",
        "excerpt": "Gioco Memory per allenare il riconoscimento dei prodotti notevoli e delle scomposizioni (Raccoglimento, Quadrati, Trinomi).",
        "tags": [
            "SCOMPOSIZIONI",
            "ALGEBRA",
            "CIT_5:IMPARARE A IMPARARE",
            "PRODOTTI NOTEVOLI",
            "EU:IMPARAREIMPARARE",
            "1 EL",
            "2 EL",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "2 GP",
            "GAMIFICATION",
            "MATEMATICA",
            "MAT:CALCOLO",
            "POLINOMI"
        ],
        "date": "2026-05-04",
        "url": "content/apps/cards_polinomi_memory004.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/cards_polinomi_memory004.jpg"
    },
    {
        "title": "C.E. Match",
        "excerpt": "Gioco Memory sul riconoscimento delle condizioni di esistenza di frazioni algebriche.",
        "tags": [
            "SCOMPOSIZIONI",
            "ALGEBRA",
            "CIT_5:IMPARARE A IMPARARE",
            "PRODOTTI NOTEVOLI",
            "EU:IMPARAREIMPARARE",
            "1 EL",
            "2 EL",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "2 GP",
            "GAMIFICATION",
            "MATEMATICA",
            "MAT:CALCOLO",
            "POLINOMI"
        ],
        "date": "2026-04-24",
        "url": "content/apps/card_frazioni_algebriche_005.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/card_frazioni_algebriche_005.jpg"
    },
    {
        "title": "Lissajous Curves 3D",
        "excerpt": "Esplorazione interattiva delle curve di Lissajous in 2D e 3D. Simulatore matematico con morphing sferico e decadimento visivo.",
        "tags": [
            "3D",
            "LABORATORIO",
            "OSCILLAZIONI",
            "LISSAJOUS",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "GEOMETRIA",
            "MATEMATICA",
            "WEBGL",
            "ONDE",
            "DIDATTICA",
            "FISICA"
        ],
        "date": "2026-04-21",
        "url": "content/apps/lissajous_curves_01.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/lissajous_curves_01.jpg"
    },
    {
        "title": "$\\pi$ is irrational",
        "excerpt": "Simulatore ultra-high res. della costante $\\pi$. Esplorazione dell'incommensurabilità con morfing sferico e shader glow.",
        "tags": [
            "PI GRECO",
            "3D",
            "$\\PI$",
            "ROTAZIONE",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "GEOMETRIA",
            "MATEMATICA",
            "WEBGL",
            "INCOMMENSURABILITÀ",
            "SHADER",
            "GLOW"
        ],
        "date": "2026-04-21",
        "url": "content/apps/pi_is_irrational.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/pi_is_irrational.jpg"
    },
    {
        "title": "$\\sqrt{2}$ is irrational",
        "excerpt": "Simulatore sferico dell'Albero di Pitagora. Algoritmo di Soft Fusion per eliminare artefatti di complanarità e mostrare l'irrazionalità di $\\sqrt{2}$.",
        "tags": [
            "3D",
            "ALBERO PITAGORICO",
            "$\\SQRT{2}$",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "FRATTALI",
            "SQRT(2)",
            "GEOMETRIA",
            "MATEMATICA",
            "WEBGL",
            "SOFT FUSION",
            "INCOMMENSURABILITÀ"
        ],
        "date": "2026-04-21",
        "url": "content/apps/sqrt2_is_irrational.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/sqrt2_is_irrational.jpg"
    },
    {
        "title": "Allegato Dlgs (Parte 61) 2017",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Allegato, Dlgs61, Funzioni..",
        "tags": [
            "LIMITI",
            "3 MEC",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "FUNZIONI",
            "INSIEMI",
            "RETTA",
            "ALLEGATO",
            "DLGS61"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_allegato",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/Allegato-A_dlgs61_2017.pdf",
        "type": "normativa",
        "icon": "📈",
        "game_type": "sim"
    },
    {
        "title": "Dlgs (Parte 61) 2017",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Dlgs, Funzioni, Limiti..",
        "tags": [
            "LIMITI",
            "MAT_K4:STATISTICA DESCRITTIVA E PROBABILITÀ",
            "STATISTICA",
            "3 MEC",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "ELETTRICITÀ",
            "INSIEMI",
            "DLGS",
            "RETTA",
            "FUNZIONI"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_elettricità",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/dlgs-61-2017.pdf",
        "type": "normativa",
        "icon": "📈",
        "game_type": "sim"
    },
    {
        "title": "Allegato (Parte 1) Competenze Pecup Professionali Area Generale Def (Parte 1)",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Allegato, Competenze, Pecup..",
        "tags": [
            "MAT_A4:APPLICARE PROPRIETÀ GEOMETRICHE IN CONTESTI O",
            "3 MEC",
            "GRAFICI",
            "ALLEGATO",
            "COMPETENZE",
            "PITAGORA",
            "TRIGONOMETRIA",
            "MAT_A4:APPLICARE PROPRIETÀ GEOMETRICHE IN CONTESTI O...",
            "PECUP",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "EQUAZIONI",
            "GEOMETRIA",
            "PROBABILITÀ",
            "MAT_K4:STATISTICA DESCRITTIVA E PROBABILITÀ",
            "STATISTICA",
            "SCOMPOSIZIONE",
            "DISEQUAZIONI",
            "INSIEMI",
            "FUNZIONI",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "RETTA",
            "POLINOMI"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_equazioni",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/ALLEGATO-1_-Competenze-pecup-professionali-area-generale-Def-1.pdf",
        "type": "normativa",
        "icon": "🧱",
        "game_type": "sim"
    },
    {
        "title": "Linee Guida Parte Prima Seconda",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Linee, Guida, Parte..",
        "tags": [
            "PARTE",
            "LIMITI",
            "MAT_K4:STATISTICA DESCRITTIVA E PROBABILITÀ",
            "STATISTICA",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "3 MEC",
            "LINEE",
            "GUIDA",
            "INSIEMI",
            "RETTA",
            "FUNZIONI"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_guida",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/Linee-guida_PARTE-PRIMA-e-SECONDA.pdf",
        "type": "normativa",
        "icon": "📈",
        "game_type": "sim"
    },
    {
        "title": "Decreto Legislativo (Parte 13) (Parte 4) 2017 (Parte 61)",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Decreto, Legislativo, Funzioni..",
        "tags": [
            "LIMITI",
            "MAT_K4:STATISTICA DESCRITTIVA E PROBABILITÀ",
            "STATISTICA",
            "LEGISLATIVO",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "3 MEC",
            "INSIEMI",
            "DECRETO",
            "RETTA",
            "FUNZIONI"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_statistica",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/decreto-legislativo-13-04-2017-n-61.pdf",
        "type": "normativa",
        "icon": "📈",
        "game_type": "sim"
    },
    {
        "title": "Il triangolo di Sierpinski",
        "excerpt": "Visualizzazione geometrica della costruzione ricorsiva del triangolo di Sierpinski in tre dimensioni. Al crescere delle iterazioni l'area diminuisce ogni volta di 1/4, tendendo a 0, ma il perimetro aumenta, tendendo all'infinito!",
        "tags": [
            "3D",
            "IND_C1:MODELLAZIONE ALGORITMICA E PARAMETRICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "FRATTALI",
            "MAT_C4:UTILIZZARE CONCETTI E MODELLI GEOMETRICI",
            "GEOMETRIA",
            "SIERPINSKI",
            "VIDEO"
        ],
        "date": "2026-04-10",
        "group_ref": "sierpinski (parte 1)",
        "version_label": "Versione Unica",
        "url": "content/video/sierpinski01.mp4",
        "type": "video",
        "icon": "🎬",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/sierpinski01.jpg"
    },
    {
        "title": "Sistemi di disequazioni vs. disequazioni frazionarie",
        "excerpt": "Nonostante dal punto di vista del calcolo sistemi di disequazioni e disequazioni frazionarie siano molto simili, è importante sottolineare che l'interpretazione delle soluzioni è diversa nei due casi. Nei sistemi, due 'sfighe' non fanno una gioia, mentre nel caso delle disequazioni frazionarie due segni negativi fanno un segno positivo.",
        "tags": [
            "ALGEBRA",
            "CIT_6:COMPETENZE SOCIALI E CIVICHE",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "DISEQUAZIONI",
            "PROBABILITÀ",
            "VIDEO"
        ],
        "date": "2026-04-03",
        "group_ref": "disequazioni duesfighe",
        "version_label": "Versione Unica",
        "url": "content/video/diseq_duesfighe.mp4",
        "type": "video",
        "icon": "🎬",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/diseq_duesfighe.jpg"
    },
    {
        "title": "$\\phi$ is irrational",
        "excerpt": "Esplorazione interattiva 2D/3D del modulo aureo ($\\phi$). Simulatore WebGL per dimostrare l'incommensurabilità attraverso le proiezioni concentriche della spirale.",
        "tags": [
            "3D",
            "SPIRALE",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "FRATTALI",
            "$\\PHI$",
            "GEOMETRIA",
            "MATEMATICA",
            "WEBGL",
            "INCOMMENSURABILITÀ"
        ],
        "date": "2026-04-03",
        "url": "content/apps/phi_is_irrational_01.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/phi_is_irrational_01.jpg"
    },
    {
        "title": "Il metodo di esaustione",
        "excerpt": "Visualizzazione parametrica del limite delle aree di poligoni regolari al crescere del numero dei lati per approssimare l'area del cerchio.",
        "tags": [
            "PI GRECO",
            "POLIGONI",
            "ESAUSTIONE",
            "LIMITI",
            "P5JS",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "AREA",
            "GEOMETRIA",
            "ARCHIMEDE",
            "MATEMATICA"
        ],
        "date": "2026-04-03",
        "url": "content/apps/esaustione_01.html",
        "type": "app",
        "icon": "📈",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/esaustione_01.jpg"
    },
    {
        "title": "Esploratore Grafico: Operazioni con i Polinomi",
        "excerpt": "Esploratore grafico per polinomi che permette di visualizzare l'effetto delle operazioni (Addizione, Sottrazione) sulle funzioni risultanti.",
        "tags": [
            "ALGEBRA",
            "EQUAZIONI FRAZIONARIE",
            "SCOMPOSIZIONE",
            "1 EL",
            "FUNZIONI FRAZIONARIE",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "2 EL",
            "3 MEC",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "2 GP",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "4 EL",
            "MAT_A2:RAPPRESENTARE DATI MEDIANTE TABELLE, GRAFICI ...",
            "GRAFICO",
            "POLINOMI"
        ],
        "date": "2026-04-02",
        "url": "content/apps/operazioni_polinomi_graph.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/operazioni_polinomi_graph.jpg"
    },
    {
        "title": "Sistemi di disequazioni vs disequazioni frazionarie",
        "excerpt": "Risolutore simbolico e interattivo per disequazioni frazionarie e sistemi matematici. Integra un tutor socratico passo passo per l'apprendimento guidato.",
        "tags": [
            "ALGEBRA",
            "SISTEMI",
            "TUTOR",
            "LOGICA",
            "1 EL",
            "2 EL",
            "3 MEC",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "RISOLUTORE",
            "DISEQUAZIONI",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "2 GP",
            "FRAZIONARIE",
            "4 EL",
            "MAT_C2:UTILIZZARE STRATEGIE DEL PENSIERO RAZIONALE P..."
        ],
        "date": "2026-04-02",
        "url": "content/apps/disequazioni_frazionarie_vs_sistemi.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/disequazioni_frazionarie_vs_sistemi.jpg"
    },
    {
        "title": "Decodifica La Matematica",
        "excerpt": "Risorsa: Decodifica La Matematica",
        "tags": [
            "INFOGRAFICA",
            "DECODIFICA",
            "VISUAL",
            "MATEMATICA"
        ],
        "date": "2025-12-15",
        "group_ref": "decodifica matematica",
        "version_label": "Versione Unica",
        "url": "content/infografiche/decodifica_la_matematica.pdf",
        "type": "infographic",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/decodifica_la_matematica.jpg"
    },
    {
        "title": "Errori Comuni - Potenze, Espressioni",
        "excerpt": "Risorsa: Errori Comuni. Prontuario per evitare gli errori più comuni nel calcolo di espressioni.",
        "tags": [
            "CALCOLO",
            "ESPRESSIONI",
            "INFOGRAFICA",
            "ERRORI COMUNI",
            "1 EL",
            "ERRORI",
            "VISUAL",
            "POTENZE",
            "PEMDAS"
        ],
        "date": "2025-12-15",
        "group_ref": "errori comuni (parte 2)",
        "version_label": "Versione Unica",
        "url": "content/infografiche/errori_comuni02.png",
        "type": "infographic",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/errori_comuni02.jpg"
    },
    {
        "date": "2025-12-12",
        "description": "Applicazione intelligente sperimentale sviluppata con Google AI Studio. Offre supporto avanzato e analisi contestuale.",
        "tags": [
            "GEMINI",
            "GOOGLE",
            "STRUMENTI",
            "LINKOGRAFIA",
            "AI",
            "SOFT_3:COMUNICAZIONE EFFICACE E LAVORO DI SQUADRA",
            "ASSISTANT"
        ],
        "title": "Google AI Studio: Assistant",
        "url": "https://ais-pre-evi2uqxownrirtwtzubadt-238287108414.europe-west2.run.app/",
        "excerpt": "Applicazione intelligente sperimentale sviluppata con Google AI Studio. Offre supporto avanzato e analisi contestuale.",
        "type": "link",
        "icon": "🌐",
        "game_type": "standard"
    },
    {
        "title": "Guida Al Mondo Delle Funzioni Matematiche",
        "excerpt": "Risorsa: Guida Al Mondo Delle Funzioni Matematiche",
        "tags": [
            "MONDO",
            "INFOGRAFICA",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "GUIDA",
            "DELLE",
            "VISUAL"
        ],
        "date": "2025-12-12",
        "group_ref": "guida mondo delle funzioni matematiche",
        "version_label": "Versione Unica",
        "url": "content/infografiche/guida_al_mondo_delle_funzioni_matematiche.pdf",
        "type": "infographic",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/guida_al_mondo_delle_funzioni_matematiche.jpg"
    },
    {
        "title": "Tattoo Delta",
        "excerpt": "Risorsa: Tattoo Delta",
        "tags": [
            "GALLERY",
            "DELTA",
            "TATTOO",
            "IMMAGINE"
        ],
        "date": "2025-12-12",
        "group_ref": "tattoo matematico delta",
        "version_label": "Versione Unica",
        "url": "content/images/tattoo_delta.png",
        "type": "image",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/tattoo_delta.jpg"
    },
    {
        "title": "PIP",
        "excerpt": "Terminale didattico Orfini Industries. Simulatore open source per lo studio della retta (y=mx+q).",
        "tags": [
            "PENDENZA",
            "3 MEC",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "2 PUNTI",
            "GAMIFICATION",
            "FALLOUT",
            "MATEMATICA",
            "RETTA",
            "4 EL",
            "GEOMETRIA ANALITICA"
        ],
        "date": "2025-12-12",
        "url": "content/apps/retta_fallout_002.html",
        "type": "app",
        "icon": "📐",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/retta_fallout_002.jpg"
    },
    {
        "title": "Percent Lab",
        "excerpt": "Laboratorio interattivo sulle percentuali. Visualizzazione, calcolo mentale e gamification.",
        "tags": [
            "1 EL",
            "GAMIFICATION",
            "ARITMETICA",
            "MATEMATICA",
            "CALCOLO MENTALE",
            "PERCENTUALI"
        ],
        "date": "2025-12-10",
        "url": "content/apps/percentuali_001.html",
        "type": "app",
        "icon": "🍰",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/percentuali_001.jpg"
    },
    {
        "title": "Studio di Funzioni: Lab Analisi + AI",
        "excerpt": "Suite completa per lo studio di funzioni reali: dominio, simmetrie, classificazione e composizione. Grafici interattivi e analisi in tempo reale powered by Gemini.",
        "tags": [
            "GEMINI",
            "STUDIO DI FUNZIONE",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "AI",
            "ANALISI",
            "DOMINIO",
            "SOFT_3:COMUNICAZIONE EFFICACE E LAVORO DI SQUADRA",
            "GRAFICI",
            "MATEMATICA",
            "FUNZIONI",
            "EDUCATION",
            "MAT_A2:RAPPRESENTARE DATI MEDIANTE TABELLE, GRAFICI ..."
        ],
        "date": "2025-12-10",
        "url": "content/apps/functions_lab_008.html",
        "type": "app",
        "icon": "📈",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/functions_lab_008.jpg"
    },
    {
        "title": "Laboratorio di operazioni tra Frazioni",
        "excerpt": "Simulatore interattivo per comprendere le operazioni tra frazioni (Somma, Prodotto, Potenza) attraverso modelli visivi (Torte) e retta numerica.",
        "tags": [
            "NUMERI RAZIONALI",
            "MAT:MODELLIZZAZIONE",
            "1 EL",
            "2 EL",
            "LAB",
            "2 GP",
            "EU:STEM",
            "MATEMATICA",
            "ARITMETICA",
            "MAT:CALCOLO",
            "FRAZIONI"
        ],
        "date": "2025-12-08",
        "url": "content/apps/fractions_lab_001.html",
        "type": "app",
        "icon": "🍰",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/fractions_lab_001.jpg"
    },
    {
        "title": "Guida 3D: Scomposizione di Polinomi (Algebra Tiles)",
        "excerpt": "Laboratorio interattivo 2D/3D per visualizzare la fattorizzazione di polinomi come aree e volumi. Include esportazione STL per la stampa 3D dei kit didattici.",
        "tags": [
            "ALGEBRA",
            "MAT:GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "1 EL",
            "2 EL",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "LAB",
            "STAMPA 3D",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "2 GP",
            "IND:STRUMENTAZIONE",
            "EU:STEM",
            "MATEMATICA",
            "GEOMETRIA",
            "POLINOMI"
        ],
        "date": "2025-12-08",
        "url": "content/apps/visualizzatore polinomi 2d 3d 001.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/visualizzatore polinomi 2d 3d 001.jpg"
    },
    {
        "title": "GonioMatch: Memory su valori notevoli di funzioni goniometriche",
        "excerpt": "Arcade educativo per allenare il riconoscimento immediato dei valori trigonometrici (Seno, Coseno) sulla circonferenza goniometrica.",
        "tags": [
            "TRIGONOMETRIA",
            "4 EL",
            "3 MEC",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "LAB",
            "MAT:ANALISI",
            "GONIOMETRIA",
            "GAMIFICATION",
            "MATEMATICA",
            "FUNZIONI",
            "ANGOLI"
        ],
        "date": "2025-12-08",
        "url": "content/apps/gioco_sin_cos_01.html",
        "type": "app",
        "icon": "📈",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/gioco_sin_cos_01.jpg"
    },
    {
        "title": "Albero di Pitagora: Frattali 3D",
        "excerpt": "Simulazione WebGL dell'Albero di Pitagora in 3D. Un'esplorazione visiva dei frattali e delle relazioni geometriche tra i quadrati.",
        "tags": [
            "CODING",
            "MAT:GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "MAT_A4:APPLICARE PROPRIETÀ GEOMETRICHE IN CONTESTI O...",
            "RICORSIONE",
            "1 EL",
            "2 EL",
            "3 MEC",
            "LAB",
            "STAMPA 3D",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "2 GP",
            "FRATTALI",
            "EU:STEM",
            "MATEMATICA",
            "GEOMETRIA",
            "PITAGORA",
            "ALGORITMI"
        ],
        "date": "2025-12-08",
        "url": "content/apps/albero_pitagorico_3d_gemini_001.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/albero_pitagorico_3d_gemini_001.jpg"
    },
    {
        "title": "AlgebraLab 3D: Scomposizione di polinomi attraverso prodotti notevoli e trinomio speciale",
        "excerpt": "Simulatore 3D interattivo per visualizzare prodotti notevoli e scomposizioni come aree e volumi.",
        "tags": [
            "ALGEBRA",
            "MAT:GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "VISUALIZZAZIONE",
            "1 EL",
            "2 EL",
            "3 MEC",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "LAB",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "2 GP",
            "EU:STEM",
            "MATEMATICA",
            "GEOMETRIA",
            "4 EL"
        ],
        "date": "2025-12-08",
        "url": "content/apps/scomp_3d_grafica_002.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/scomp_3d_grafica_002.jpg"
    },
    {
        "title": "Parabola Challenge: Disequazioni",
        "excerpt": "Videogioco didattico a livelli sulle disequazioni di secondo grado. Scaffolding progressivo fino all'input testuale libero.",
        "tags": [
            "ALGEBRA",
            "SCAFFOLDING",
            "3 MEC",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "PARABOLA",
            "MAT:ANALISI",
            "DISEQUAZIONI",
            "GAMIFICATION",
            "MATEMATICA",
            "4 EL",
            "MAT:PROBLEMSOLVING"
        ],
        "date": "2025-12-08",
        "url": "content/apps/disequazioni grafiche 4el.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/disequazioni grafiche 4el.jpg"
    },
    {
        "title": "Simulazione CA: Fasori & Onde",
        "excerpt": "Simulatore interattivo del comportamento in Corrente Alternata (Sfasamento, Valori Efficaci, Potenza) per il corso di macchine elettriche.",
        "tags": [
            "MAT:MODELLIZZAZIONE",
            "CORRENTE ALTERNATA",
            "LAB",
            "MAT:ANALISI",
            "ELETTROTECNICA",
            "IND:STRUMENTAZIONE",
            "4 EL",
            "FASORI",
            "ONDE",
            "FISICA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/corrente_4el_sincos.html",
        "type": "app",
        "icon": "⚡",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/corrente_4el_sincos.jpg"
    },
    {
        "title": "Esploratore Numerico: Pitagora & Tartaglia",
        "excerpt": "Laboratorio interattivo per scoprire i pattern dei numeri: Tavola Pitagorica (Primi, Quadrati), Triangolo di Tartaglia (Combinatoria) e regole di divisibilità.",
        "tags": [
            "DIVISIBILITÀ",
            "MAT:MODELLIZZAZIONE",
            "MAT_A4:APPLICARE PROPRIETÀ GEOMETRICHE IN CONTESTI O...",
            "MAT:DATI",
            "1 EL",
            "2 EL",
            "LAB",
            "MAT_C3:ANALIZZARE DATI E INTERPRETARE INFORMAZIONI C...",
            "2 GP",
            "NUMERI",
            "ARITMETICA",
            "MATEMATICA",
            "4 EL",
            "MAT:CALCOLO",
            "PITAGORA",
            "TARTAGLIA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/tavola_tart_canva0003.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/tavola_tart_canva0003.jpg"
    },
    {
        "title": "Sketch to Pattern: Arte Generativa",
        "excerpt": "Strumento di arte generativa che trasforma schizzi a mano libera in pattern geometrici complessi. Sperimenta con algoritmi, semplificazione e tassellazioni.",
        "tags": [
            "EU:DIGITALE",
            "EU:CULTURALE",
            "CODING",
            "CREATIVITÀ",
            "LAB",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "CIT_4:COMPETENZA DIGITALE",
            "GEOMETRIA",
            "TECNOLOGIA",
            "TINKERING",
            "ARTE",
            "PATTERN"
        ],
        "date": "2025-12-08",
        "url": "content/apps/sketch_to_pattern_gemini_005.html",
        "type": "app",
        "icon": "📐",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/sketch_to_pattern_gemini_005.jpg"
    },
    {
        "title": "Logic Lab: Insiemi & Venn",
        "excerpt": "Laboratorio interattivo per esplorare la Teoria degli Insiemi. Definisci gli elementi, componi espressioni logiche (Unione, Intersezione) e visualizza i Diagrammi di Venn in tempo reale.",
        "tags": [
            "DIAGRAMMI DI VENN",
            "MAT:MODELLIZZAZIONE",
            "LOGICA",
            "1 EL",
            "2 EL",
            "MAT_C2:UTILIZZARE STRATEGIE DEL PENSIERO RAZIONALE P...",
            "LAB",
            "INSIEMI",
            "2 GP",
            "EU:STEM",
            "MATEMATICA",
            "MAT:LOGICA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/insiemi004.html",
        "type": "app",
        "icon": "🔴",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/insiemi004.jpg"
    },
    {
        "title": "Mappe & Distorsioni: Mercatore",
        "excerpt": "Modello interattivo in D3.js per esplorare le distorsioni della proiezione di Mercatore confrontando le aree reali dei paesi.",
        "tags": [
            "PROIEZIONI",
            "MAT:GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "COORDINATE",
            "1 EL",
            "2 EL",
            "LAB",
            "SCALA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "2 GP",
            "GEOGRAFIA",
            "EU:STEM",
            "MATEMATICA",
            "MERCATORE"
        ],
        "date": "2025-12-08",
        "url": "content/apps/mercatore_correzione_001_gemini_worksproperly.html",
        "type": "app",
        "icon": "🌍",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/mercatore_correzione_001_gemini_worksproperly.jpg"
    },
    {
        "title": "Math Underground: Mappa per la classificazione di Funzioni",
        "excerpt": "Mappa interattiva della metropolitana per lo studio teorico delle funzioni analitiche e delle loro principali proprietà (Dominio, Codominio).",
        "tags": [
            "MAT:MODELLIZZAZIONE",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "ANALISI",
            "LAB",
            "MAT:ANALISI",
            "DOMINIO",
            "MAPPA",
            "EU:STEM",
            "MATEMATICA",
            "FUNZIONI",
            "4 EL",
            "MAT_A2:RAPPRESENTARE DATI MEDIANTE TABELLE, GRAFICI ..."
        ],
        "date": "2025-12-06",
        "url": "content/apps/math_underground003_4el.html",
        "type": "app",
        "icon": "📈",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/math_underground003_4el.jpg"
    },
    {
        "title": "Math Invaders",
        "excerpt": "Laboratorio procedurale per il calcolo del Massimo Comune Divisore e Minimo Comune Multiplo tramite scomposizione in fattori primi.",
        "tags": [
            "VIDEOGIOCO",
            "1 EL",
            "MCM",
            "MCD",
            "GAMIFICATION",
            "ARITMETICA",
            "MATEMATICA",
            "MAT:CALCOLO"
        ],
        "date": "2025-12-02",
        "url": "content/apps/MCD_mcm_1el_001.html",
        "type": "app",
        "icon": "🔢",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/MCD_mcm_1el_001.jpg"
    },
    {
        "title": "Chaos Lab: Sistemi Dinamici",
        "excerpt": "Simulatore 3D di Attrattori Strani (Lorenz, Rössler, Chen). Esplora il Caos Deterministico e le Equazioni Differenziali tramite integrazione numerica RK4.",
        "tags": [
            "EU:DIGITALE",
            "CAOS",
            "MAT:MODELLIZZAZIONE",
            "2 EL",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "SISTEMI DINAMICI",
            "ANALISI",
            "MAT:ANALISI",
            "SIMULAZIONE",
            "2 GP",
            "CIT_4:COMPETENZA DIGITALE",
            "EU:STEM",
            "MATEMATICA",
            "ATTRATTORI",
            "4 EL",
            "FISICA"
        ],
        "date": "2025-10-24",
        "url": "content/apps/attrattori_001_dec25.html",
        "type": "app",
        "icon": "📈",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/attrattori_001_dec25.jpg"
    },
    {
        "title": "Caccia all'Errore: Memory su Operazioni in Z",
        "excerpt": "Missione di addestramento sui Numeri Interi (Z) e le Potenze. Trova le corrispondenze corrette ed evita le trappole degli errori comuni di calcolo.",
        "tags": [
            "ERRORI COMUNI",
            "NUMERI INTERI",
            "1 EL",
            "Z",
            "GAMIFICATION",
            "EU:STEM",
            "MATEMATICA",
            "ARITMETICA",
            "MAT:CALCOLO",
            "MAT:PROBLEMSOLVING",
            "POTENZE"
        ],
        "date": "2025-10-20",
        "url": "content/apps/memory_1el_numeri_004.html",
        "type": "app",
        "icon": "🔢",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/memory_1el_numeri_004.jpg"
    }
];