/* 
   ⚠️ GENERATO AUTOMATICAMENTE DA build.py 
   Data: 2026-10-05 10:57:13
*/

const db = [
    {
        "title": "AI Math Assistant: Tutor Didattico Sperimentale",
        "url": "https://ais-pre-evi2uqxownrirtwtzubadt-238287108414.europe-west2.run.app/",
        "type": "link",
        "description": "Assistente conversazionale basato su modelli linguistici per la didattica della matematica: guida lo studente nel ragionamento socratico, nell'analisi degli errori e nella formulazione di ipotesi.",
        "tags": [
            "AI",
            "CIT_1:COMUNICAZIONE NELLA MADRELINGUA",
            "DIDATTICA",
            "GEMINI",
            "LABORATORIO",
            "SOFT_2:METACOGNIZIONE",
            "SOFT_2:PROBLEM SOLVING E PENSIERO CRITICO",
            "SOFT_3:COMUNICAZIONE EFFICACE E LAVORO DI SQUADRA",
            "TUTOR SOCRATICO"
        ],
        "excerpt": "Assistente conversazionale basato su modelli linguistici per la didattica della matematica: guida lo studente nel ragionamento socratico, nell'analisi degli errori e nella formulazione di ipotesi.",
        "icon": "🌐",
        "game_type": "sim",
        "date": "2026-10-05"
    },
    {
        "title": "Palestra: Memory delle Scomposizioni",
        "excerpt": "Gioco Memory per allenare il riconoscimento dei prodotti notevoli e delle scomposizioni (Raccoglimento, Quadrati, Trinomi).",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "ALGEBRA",
            "CIT_5:IMPARARE A IMPARARE",
            "EU:IMPARAREIMPARARE",
            "GAMIFICATION",
            "MAT:CALCOLO",
            "MATEMATICA",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "POLINOMI",
            "PRODOTTI NOTEVOLI",
            "SCOMPOSIZIONI"
        ],
        "date": "2026-10-05",
        "url": "content/apps/cards_polinomi_memory004.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/cards_polinomi_memory004.jpg"
    },
    {
        "title": "C.E. Match",
        "excerpt": "Gioco Memory sul riconoscimento delle condizioni di esistenza di frazioni algebriche.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "ALGEBRA",
            "CIT_5:IMPARARE A IMPARARE",
            "EU:IMPARAREIMPARARE",
            "GAMIFICATION",
            "MAT:CALCOLO",
            "MATEMATICA",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "POLINOMI",
            "PRODOTTI NOTEVOLI",
            "SCOMPOSIZIONI"
        ],
        "date": "2026-10-05",
        "url": "content/apps/card_frazioni_algebriche_005.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/card_frazioni_algebriche_005.jpg"
    },
    {
        "title": "Teoria dei giochi e valutazione consapevole",
        "excerpt": "Simulazione interattiva del Dilemma del Prigioniero ed Equilibrio di Nash. Laboratorio per esplorare la cooperazione e le scelte strategiche nel contesto del voto scolastico.",
        "tags": [
            "4 EL",
            "CITTADINANZA",
            "CIT_6:COMPETENZE SOCIALI E CIVICHE",
            "CIV:COSTITUZIONE",
            "ED. CIVICA",
            "EQUILIBRIO DI NASH",
            "EU:CITTADINANZA",
            "MAT:DATI",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "MAT_C3:ANALIZZARE DATI E INTERPRETARE INFORMAZIONI CON STRUMENTI STATISTICI E PROBABILISTICI",
            "TEORIA DEI GIOCHI"
        ],
        "date": "2026-10-05",
        "url": "content/apps/voto_cosapevole.2.5.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/voto_cosapevole.2.5.jpg"
    },
    {
        "title": "PixelGrid",
        "excerpt": "Applicazione di Game Theory all'analisi delle radici nelle equazioni di secondo grado, esplorando l'ottimizzazione e le strategie dominanti.",
        "tags": [
            "3 MEC",
            "4 EL",
            "ALGEBRA",
            "EQUAZIONI DI SECONDO GRADO",
            "FATTORIZZAZIONE",
            "G",
            "ITA",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "MODELLIZZAZIONE",
            "PARABOLA",
            "POLINOMI",
            "PRODOTTI NOTEVOLI",
            "QUADRATICHE",
            "SCOMPOSIZIONE"
        ],
        "date": "2026-10-05",
        "url": "content/apps/eq_2_gr_teoria_giochi_01.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/eq_2_gr_teoria_giochi_01.jpg"
    },
    {
        "title": "Simulatore di Automi Cellulari e Particelle",
        "excerpt": "Laboratorio interattivo su automi cellulari e dinamica di particelle a soglia. Esplorazione visiva di sistemi complessi, transizioni di fase ed emergenza computazionale.",
        "tags": [
            "3 MEC",
            "4 EL",
            "AUTOMA CELLULARE",
            "CODING",
            "DINAMICA",
            "FISICA",
            "MATEMATICA",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "PARTICELLE",
            "SIMULAZIONE",
            "SISTEMI COMPLESSI"
        ],
        "date": "2026-10-05",
        "url": "content/apps/soglie_particelle_automa_cellulare.html",
        "type": "app",
        "icon": "⚡",
        "game_type": "sim"
    },
    {
        "title": "Le fasi della Luna",
        "excerpt": "Simulatore 3D interattivo delle fasi lunari, dell'orbita Terra-Luna e dell'illuminazione solare. Modalità didattica e realistica, rotazione sincrona, punti di vista multipli ed eclissi.",
        "tags": [
            "1 EL",
            "1 MA",
            "2 EL",
            "2 MA",
            "3D",
            "ASTRONOMIA",
            "BIENNIO",
            "ECLISSI",
            "FASI LUNARI",
            "FISICA",
            "GEOMETRIA SPAZIALE",
            "LABORATORIO",
            "LUNA",
            "MAT_C4:UTILIZZARE CONCETTI E MODELLI GEOMETRICI PER INTERPRETARE LA REALTÀ E GESTIRE CONFIGURAZIONI SPAZIALI",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "MODELLIZZAZIONE",
            "ORBITA",
            "ROTAZIONE SINCRONA",
            "SCIENZE DELLA TERRA",
            "SIMULAZIONE",
            "SISTEMA SOLARE",
            "SPAZIO",
            "THREE.JS",
            "WEBGL"
        ],
        "date": "2026-09-30",
        "url": "content/apps/le_fasi_della_luna.html",
        "type": "app",
        "icon": "🌕",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/le_fasi_della_luna.jpg"
    },
    {
        "title": "FuncLab AI: Esploratore di Funzioni",
        "excerpt": "Laboratorio interattivo di analisi matematica: piano cartesiano con zoom/pan, generatore di funzioni con AI, visualizzazione LaTeX, tratti analitici e Tutor Socratico con sintesi vocale.",
        "tags": [
            "AI",
            "ANALISI",
            "EDUCATION",
            "FUNZIONI",
            "GEMINI",
            "GRAFICI",
            "LABORATORIO",
            "MATEMATICA",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "PIANO CARTESIANO",
            "SOFT_3:COMUNICAZIONE EFFICACE E LAVORO DI SQUADRA",
            "STUDIO DI FUNZIONE",
            "TUTOR SOCRATICO"
        ],
        "date": "2026-09-09",
        "url": "content/apps/functions_lab_008.html",
        "type": "app",
        "icon": "📈",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/functions_lab_008.jpg"
    },
    {
        "title": "Studio Plotter CNC",
        "excerpt": "Generatore ed elaboratore G-Code avanzato per pen plotter e CNC, con algoritmi generativi e simulatore 3D.",
        "tags": [
            "3 MEC",
            "4 EL",
            "5 EL",
            "ALGORITMI",
            "ARTE GENERATIVA",
            "ATTRATTORI",
            "CIT_4:COMPETENZA DIGITALE",
            "CIT_7:SPIRITO DI INIZIATIVA",
            "CNC",
            "FRATTALI",
            "G-CODE",
            "IND_C1:MODELLAZIONE ALGORITMICA E PARAMETRICA",
            "IND_C2:CODING E SIMULAZIONI STEM",
            "IND_C3:FABBRICAZIONE DIGITALE 3D",
            "L-SYSTEM",
            "MANIFATTURA DIGITALE",
            "MATEMATICA",
            "MAT_C4:MODELLI GEOMETRICI E SPAZIALI",
            "MODELLAZIONE PARAMETRICA",
            "PEN PLOTTER",
            "SLICING",
            "STAMPA 3D",
            "STUDIO PLOTTER CNC",
            "TRASVERSALE"
        ],
        "date": "2026-08-27",
        "url": "content/apps/pen_plotter__23v2_8K.html",
        "type": "app",
        "icon": "📈",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/pen_plotter__23v2_8K.jpg"
    },
    {
        "title": "Challenge: Scomposizione di Polinomi (PRO)",
        "excerpt": "Versione PRO della sfida 3D sui polinomi: Ghost Target, X-Ray mode e variabili dinamiche.",
        "tags": [
            "1 EL",
            "3D",
            "ALGEBRA",
            "MATEMATICA",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "NERDAMER",
            "POLINOMI",
            "PRO",
            "SCOMPOSIZIONE"
        ],
        "date": "2026-05-27",
        "url": "content/apps/polinomi_challenge_v2_pro.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/polinomi_challenge_v2_pro.jpg"
    },
    {
        "title": "Experience Fibonacci",
        "excerpt": "Esplorazione interattiva della successione di Fibonacci, della spirale aurea e della fillotassi nei girasoli. Un'esperienza visiva per comprendere la convergenza del rapporto aureo e l'ottimizzazione geometrica in natura.",
        "tags": [
            "FIBONACCI",
            "FILLOTASSI",
            "GEOMETRIA",
            "MATEMATICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "NATURA",
            "P5.JS",
            "PHI",
            "SEZIONE AUREA",
            "SPIRALE AUREA",
            "TRASVERSALE"
        ],
        "date": "2026-05-27",
        "url": "content/apps/fibonacci_anim.html",
        "type": "app",
        "icon": "📐",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/fibonacci_anim.jpg"
    },
    {
        "title": "Esploratore di Scale Logaritmiche",
        "excerpt": "Laboratorio interattivo sulle scale logaritmiche per esplorare la crescita esponenziale, le leggi di potenza e fenomeni fisici reali.",
        "tags": [
            "4 EL",
            "5 EL",
            "ACUSTICA",
            "CRESCITA ESPONENZIALE",
            "EPIDEMIOLOGIA",
            "LABORATORIO",
            "LEGGE DI KLEIBER",
            "LEGGE DI MOORE",
            "MATEMATICA",
            "SCALE LOGARITMICHE"
        ],
        "date": "2026-05-22",
        "url": "content/apps/scale_logaritmiche.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/scale_logaritmiche.jpg"
    },
    {
        "title": "Math Pool: Biliardo Cartesiano e retta",
        "excerpt": "Laboratorio interattivo e gamification di Geometria Analitica: gioca a biliardo sul piano cartesiano calcolando l'equazione della retta, coefficiente angolare e punti di intersezione per mandare la palla in buca.",
        "tags": [
            "2 GP",
            "3 MEC",
            "BILIARDO",
            "GAMIFICATION",
            "GEOMETRIA ANALITICA",
            "MATEMATICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "PIANO CARTESIANO",
            "RETTA"
        ],
        "date": "2026-05-21",
        "url": "content/apps/math_pool_retta_pianocartesiano.html",
        "type": "app",
        "icon": "📐",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/math_pool_retta_pianocartesiano.jpg"
    },
    {
        "title": "Random Walk 3D | Hypercaos & Chromatic Memory",
        "excerpt": "Simulatore interattivo di passeggiate aleatorie in 3D. Esplora il caos deterministico e la geometria frattale (Koch, Hilbert, Peano) attraverso algoritmi generativi e morphing cromatico in tempo reale.",
        "tags": [
            "3D",
            "4 EL",
            "5 EL",
            "ALGORITMI",
            "CAOS",
            "FRATTALI",
            "IND_C2:CODING",
            "MAT_K3:GEOMETRIA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "RANDOM WALK",
            "SOFT_2:METACOGNIZIONE",
            "SOFT_2:PROBLEM SOLVING E PENSIERO CRITICO",
            "WEBGL"
        ],
        "date": "2026-05-16",
        "url": "content/apps/random_walk.html",
        "type": "app",
        "icon": "🌀",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/random_walk.jpg"
    },
    {
        "title": "Laboratorio Scomposizioni e Disequazioni di secondo grado | Parabola",
        "excerpt": "Ambiente di studio sinottico per lo studio delle disequazioni di secondo grado. Include scomposizione in fattori, metodo del delta, diagrammi dei segni e visualizzazione grafica della parabola in tempo reale.",
        "tags": [
            "3 MEC",
            "4 EL",
            "ALGEBRA",
            "DIDATTICA INCLUSIVA",
            "DISEQUAZIONI DI SECONDO GRADO",
            "LABORATORIO METACOGNITIVO",
            "MAT_A3:EQUAZIONI E DISEQUAZIONI",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:ALGEBRA",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "PARABOLA",
            "SCOMPOSIZIONI"
        ],
        "date": "2026-05-16",
        "url": "content/apps/parabola e disequazioni di secondo grado maggio 2026.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/parabola e disequazioni di secondo grado maggio 2026.jpg"
    },
    {
        "date": "2026-05-13",
        "description": "Esercitazione interattiva su GeoGebra per lo studio della retta passante per due punti. Esplorazione dinamica dei parametri.",
        "tags": [
            "2 GP",
            "GEOGEBRA",
            "GEOMETRIA ANALITICA",
            "LABORATORIO",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "RETTA"
        ],
        "title": "Esercitazione GeoGebra: Retta per due punti",
        "url": "https://www.geogebra.org/m/mcfvzdfx",
        "excerpt": "Esercitazione interattiva su GeoGebra per lo studio della retta passante per due punti. Esplorazione dinamica dei parametri.",
        "type": "link",
        "icon": "🌐",
        "game_type": "sim"
    },
    {
        "title": "Lissajous Curves 3D",
        "excerpt": "Esplorazione interattiva delle curve di Lissajous in 2D e 3D. Simulatore matematico con morphing sferico e decadimento visivo.",
        "tags": [
            "3D",
            "DIDATTICA",
            "FISICA",
            "GEOMETRIA",
            "LABORATORIO",
            "LISSAJOUS",
            "MATEMATICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "ONDE",
            "OSCILLAZIONI",
            "WEBGL"
        ],
        "date": "2026-04-21",
        "url": "content/apps/lissajous_curves_01.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/lissajous_curves_01.jpg"
    },
    {
        "title": "$\\pi$ is irrational: visualizzare l'incommensurabilità",
        "excerpt": "Esplorazione geometrica e visiva del numero $\\pi$. Scopri l'incommensurabilità tra circonferenza e diametro osservando la rettificazione del cerchio e la natura non periodica delle sue cifre decimali.",
        "tags": [
            "$\\PI$",
            "3D",
            "GEOMETRIA",
            "INCOMMENSURABILITÀ",
            "IRRAZIONALITÀ",
            "MATEMATICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "PI GRECO",
            "ROTAZIONE",
            "WEBGL"
        ],
        "date": "2026-04-21",
        "url": "content/apps/pi_is_irrational.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/pi_is_irrational.jpg"
    },
    {
        "title": "$\\sqrt{2}$ is irrational: la diagonale incommensurabile",
        "excerpt": "Esplorazione visiva dell'Albero di Pitagora e della spirale dei triangoli rettangoli. Scopri perché lato e diagonale di un quadrato non possono essere misurati con la stessa unità, illustrando l'irrazionalità di $\\sqrt{2}$.",
        "tags": [
            "$\\SQRT{2}$",
            "3D",
            "ALBERO PITAGORICO",
            "FRATTALI",
            "GEOMETRIA",
            "INCOMMENSURABILITÀ",
            "IRRAZIONALITÀ",
            "MATEMATICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "SQRT(2)",
            "WEBGL"
        ],
        "date": "2026-04-21",
        "url": "content/apps/sqrt2_is_irrational.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/sqrt2_is_irrational.jpg"
    },
    {
        "title": "Allegato A - Profilo Educativo, Culturale e Professionale (PECUP)",
        "excerpt": "Allegato A al D.Lgs. 61/2017: risultati di apprendimento comuni a tutti i percorsi di istruzione professionale e declinazione delle competenze generali.",
        "tags": [
            "3 MEC",
            "ALLEGATO",
            "COMPETENZE",
            "D.LGS. 61/2017",
            "DLGS61",
            "FUNZIONI",
            "INSIEMI",
            "LIMITI",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "NORMATIVA",
            "PECUP",
            "RETTA"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_retta",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/Allegato-A_dlgs61_2017.pdf",
        "type": "normativa",
        "icon": "📈",
        "game_type": "document"
    },
    {
        "title": "D.Lgs. 61/2017 - Testo Integrale",
        "excerpt": "Testo e quadro normativo del Decreto Legislativo 61/2017 relativo alla riforma degli istituti professionali.",
        "tags": [
            "3 MEC",
            "D.LGS. 61/2017",
            "DLGS",
            "ELETTRICITÀ",
            "FUNZIONI",
            "INSIEMI",
            "LIMITI",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "MAT_K4:STATISTICA DESCRITTIVA E PROBABILITÀ",
            "NORMATIVA",
            "RETTA",
            "RIFORMA 2017",
            "STATISTICA"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_retta",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/dlgs-61-2017.pdf",
        "type": "normativa",
        "icon": "📈",
        "game_type": "document"
    },
    {
        "title": "Allegato 1 - Competenze Area Generale (PECUP)",
        "excerpt": "Competenze di indirizzo generale, asse matematico, linguistico e storico-sociale per gli istituti professionali secondo la riforma 2017.",
        "tags": [
            "3 MEC",
            "ALLEGATO",
            "ASSE MATEMATICO",
            "COMPETENZE",
            "DISEQUAZIONI",
            "EQUAZIONI",
            "FUNZIONI",
            "GEOMETRIA",
            "GRAFICI",
            "INSIEMI",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_A4:APPLICARE PROPRIETÀ GEOMETRICHE IN CONTESTI OPERATIVI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "MAT_K4:STATISTICA DESCRITTIVA E PROBABILITÀ",
            "NORMATIVA",
            "PECUP",
            "PITAGORA",
            "POLINOMI",
            "PROBABILITÀ",
            "RETTA",
            "SCOMPOSIZIONE",
            "STATISTICA",
            "TRIGONOMETRIA"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_scomposizione",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/ALLEGATO-1_-Competenze-pecup-professionali-area-generale-Def-1.pdf",
        "type": "normativa",
        "icon": "🧱",
        "game_type": "document"
    },
    {
        "title": "Linee Guida Nazionali - Parte I e II",
        "excerpt": "Linee guida ministeriali per il passaggio al nuovo ordinamento degli istituti professionali (D.Lgs. 61/2017), progettazione per UDA e certificazione delle competenze.",
        "tags": [
            "3 MEC",
            "COMPETENZE",
            "FUNZIONI",
            "INSIEMI",
            "LIMITI",
            "LINEE GUIDA",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "MAT_K4:STATISTICA DESCRITTIVA E PROBABILITÀ",
            "NORMATIVA",
            "PRIMA",
            "RETTA",
            "SECONDA",
            "STATISTICA",
            "UDA"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_retta",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/Linee-guida_PARTE-PRIMA-e-SECONDA.pdf",
        "type": "normativa",
        "icon": "📈",
        "game_type": "document"
    },
    {
        "title": "D.Lgs. 61/2017 - Revisione Percorsi Istruzione Professionale",
        "excerpt": "Decreto Legislativo 13 aprile 2017, n. 61: testo normativo fondamentale per il riordino degli istituti professionali in attuazione dell'articolo 1, commi 180 e 181, lettera d), della legge n. 107/2015.",
        "tags": [
            "3 MEC",
            "D.LGS. 61/2017",
            "DECRETO",
            "FUNZIONI",
            "INSIEMI",
            "ISTITUTI PROFESSIONALI",
            "LEGISLATIVO",
            "LIMITI",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "MAT_K4:STATISTICA DESCRITTIVA E PROBABILITÀ",
            "NORMATIVA",
            "RETTA",
            "RIFORMA 2017",
            "STATISTICA"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_retta",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/decreto-legislativo-13-04-2017-n-61.pdf",
        "type": "normativa",
        "icon": "📈",
        "game_type": "document"
    },
    {
        "title": "Il Triangolo di Sierpinski (Video)",
        "excerpt": "Costruzione ricorsiva del frattale di Sierpinski animata con Manim. A ogni passo l'area viene moltiplicata per 3/4 (tendendo a zero), mentre il perimetro viene moltiplicato per 3/2 (tendendo all'infinito): un'area nulla racchiusa da un confine infinito!",
        "tags": [
            "FRATTALI",
            "GEOMETRIA",
            "IND_C1:MODELLAZIONE ALGORITMICA E PARAMETRICA",
            "MANIM",
            "MAT_C4:MODELLI GEOMETRICI E SPAZIALI",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "RICORSIONE",
            "SIERPINSKI",
            "VIDEO"
        ],
        "date": "2026-04-10",
        "group_ref": "sierpinski (parte 1)",
        "version_label": "Versione Unica",
        "url": "content/video/sierpinski01.mp4",
        "type": "video",
        "icon": "🎬",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/sierpinski01.jpg"
    },
    {
        "title": "Video: Sistemi vs Disequazioni frazionarie (\"Due sfighe non fanno una gioia\")",
        "excerpt": "Perché dal punto di vista del calcolo sembrano simili ma concettualmente sono opposti: nei sistemi cerchiamo le intersezioni (due 'sfighe' non fanno una gioia!), nelle frazionarie studiamo il segno (meno per meno fa più).",
        "tags": [
            "ALGEBRA",
            "CIT_6:COMPETENZE SOCIALI E CIVICHE",
            "DISEQUAZIONI",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "PROBABILITÀ",
            "REGOLA DEI SEGNI",
            "SISTEMI",
            "VIDEO"
        ],
        "date": "2026-04-03",
        "group_ref": "disequazioni duesfighe",
        "version_label": "Versione Unica",
        "url": "content/video/diseq_duesfighe.mp4",
        "type": "video",
        "icon": "🎬",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/diseq_duesfighe.jpg"
    },
    {
        "title": "$\\phi$ is irrational: il rapporto aureo",
        "excerpt": "Esplorazione visiva del numero aureo ($\\phi$) e della spirale logaritmica. Un'esperienza interattiva per visualizzare le frazioni continue, la fillotassi e l'incommensurabilità della proporzione aurea in natura.",
        "tags": [
            "$\\PHI$",
            "3D",
            "FILLOTASSI",
            "GEOMETRIA",
            "INCOMMENSURABILITÀ",
            "MATEMATICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "RAPPORTO AUREO",
            "SEZIONE AUREA",
            "SPIRALE",
            "WEBGL"
        ],
        "date": "2026-04-03",
        "url": "content/apps/phi_is_irrational_01.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/phi_is_irrational_01.jpg"
    },
    {
        "title": "Il metodo di esaustione",
        "excerpt": "Visualizzazione parametrica del limite delle aree di poligoni regolari al crescere del numero dei lati per approssimare l'area del cerchio.",
        "tags": [
            "ARCHIMEDE",
            "AREA",
            "ESAUSTIONE",
            "GEOMETRIA",
            "LIMITI",
            "MATEMATICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "P5JS",
            "PI GRECO",
            "POLIGONI"
        ],
        "date": "2026-04-03",
        "url": "content/apps/esaustione_01.html",
        "type": "app",
        "icon": "📈",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/esaustione_01.jpg"
    },
    {
        "title": "Esploratore Grafico: Operazioni con i Polinomi",
        "excerpt": "Esploratore grafico per polinomi che permette di visualizzare l'effetto delle operazioni (Addizione, Sottrazione) sulle funzioni risultanti.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "3 MEC",
            "4 EL",
            "ALGEBRA",
            "EQUAZIONI FRAZIONARIE",
            "FUNZIONI FRAZIONARIE",
            "GRAFICO",
            "MAT_A2:RAPPRESENTARE DATI MEDIANTE TABELLE, GRAFICI E FUNZIONI",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "POLINOMI",
            "SCOMPOSIZIONE"
        ],
        "date": "2026-04-02",
        "url": "content/apps/operazioni_polinomi_graph.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/operazioni_polinomi_graph.jpg"
    },
    {
        "title": "Laboratorio Interattivo: Sistemi vs Disequazioni frazionarie",
        "excerpt": "Risolutore simbolico passo-passo con Tutor Socratico integrato: metti a confronto la regola dei segni nelle frazionarie con l'intersezione delle soluzioni nei sistemi, senza più fare confusione alla lavagna o sul quaderno.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "3 MEC",
            "4 EL",
            "ALGEBRA",
            "DISEQUAZIONI",
            "FRAZIONARIE",
            "LOGICA",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_C2:UTILIZZARE STRATEGIE DEL PENSIERO RAZIONALE PER AFFRONTARE SITUAZIONI PROBLEMATICHE IN CONTESTI REALI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "RISOLUTORE",
            "SISTEMI",
            "TUTOR"
        ],
        "date": "2026-04-02",
        "url": "content/apps/disequazioni_frazionarie_vs_sistemi.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/disequazioni_frazionarie_vs_sistemi.jpg"
    },
    {
        "title": "Decodifica la Matematica: grammatica dei simboli",
        "excerpt": "Smetti di indovinare, inizia a capire: prontuario visuale per decodificare il formalismo, i simboli e la sintassi matematica, trasformando un insieme di regole mnemoniche in un linguaggio chiaro e accessibile.",
        "tags": [
            "DECODIFICA",
            "DIDATTICA INCLUSIVA",
            "INFOGRAFICA",
            "LINGUAGGIO MATEMATICO",
            "MATEMATICA",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "SIMBOLI",
            "VISUAL"
        ],
        "date": "2025-12-15",
        "group_ref": "decodifica matematica",
        "version_label": "Versione Unica",
        "url": "content/infografiche/decodifica_la_matematica.pdf",
        "type": "infographic",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/decodifica_la_matematica.jpg"
    },
    {
        "title": "Errori Comuni - Potenze, Espressioni",
        "excerpt": "Risorsa: Errori Comuni. Prontuario per evitare gli errori più comuni nel calcolo di espressioni.",
        "tags": [
            "1 EL",
            "CALCOLO",
            "ERRORI",
            "ERRORI COMUNI",
            "ESPRESSIONI",
            "INFOGRAFICA",
            "PEMDAS",
            "POTENZE",
            "VISUAL"
        ],
        "date": "2025-12-15",
        "group_ref": "errori comuni (parte 2)",
        "version_label": "Versione Unica",
        "url": "content/infografiche/errori_comuni02.png",
        "type": "infographic",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/errori_comuni02.jpg"
    },
    {
        "title": "Guida al Mondo delle Funzioni Matematiche",
        "excerpt": "Mappa concettuale e infografica sinottica per orientarsi tra dominio, codominio, proprietà (iniettività, suriettività) e classificazione analitica delle funzioni elementari.",
        "tags": [
            "ANALISI MATEMATICA",
            "CODOMINIO",
            "DOMINIO",
            "FUNZIONI",
            "INFOGRAFICA",
            "MATEMATICHE",
            "MAT_A2:RAPPRESENTARE DATI MEDIANTE TABELLE, GRAFICI E FUNZIONI",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "VISUAL"
        ],
        "date": "2025-12-12",
        "group_ref": "guida mondo delle funzioni matematiche",
        "version_label": "Versione Unica",
        "url": "content/infografiche/guida_al_mondo_delle_funzioni_matematiche.pdf",
        "type": "infographic",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/guida_al_mondo_delle_funzioni_matematiche.jpg"
    },
    {
        "title": "Formula del Delta: $\\Delta = b^2 - 4ac$ (Tattoo)",
        "excerpt": "Il discriminante delle equazioni di secondo grado impresso sulla pelle: un promemoria visivo e ironico per ricordare una volta per tutte che il segno del $\\Delta$ decide quante soluzioni reali esistono.",
        "tags": [
            "ALGEBRA",
            "DELTA",
            "DISCRIMINANTE",
            "EQUAZIONI DI SECONDO GRADO",
            "IMMAGINE",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "PARABOLA",
            "TATTOO"
        ],
        "date": "2025-12-12",
        "group_ref": "tattoo matematico delta",
        "version_label": "Versione Unica",
        "url": "content/images/tattoo_delta.png",
        "type": "image",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/tattoo_delta.jpg"
    },
    {
        "title": "PIP",
        "excerpt": "Terminale didattico Orfini Industries. Simulatore open source per lo studio della retta (y=mx+q).",
        "tags": [
            "2 PUNTI",
            "3 MEC",
            "4 EL",
            "FALLOUT",
            "GAMIFICATION",
            "GEOMETRIA ANALITICA",
            "MATEMATICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "PENDENZA",
            "RETTA"
        ],
        "date": "2025-12-12",
        "url": "content/apps/retta_fallout_002.html",
        "type": "app",
        "icon": "📐",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/retta_fallout_002.jpg"
    },
    {
        "title": "Percent Lab",
        "excerpt": "Laboratorio interattivo sulle percentuali. Visualizzazione, calcolo mentale e gamification.",
        "tags": [
            "1 EL",
            "ARITMETICA",
            "CALCOLO MENTALE",
            "GAMIFICATION",
            "MATEMATICA",
            "PERCENTUALI"
        ],
        "date": "2025-12-10",
        "url": "content/apps/percentuali_001.html",
        "type": "app",
        "icon": "🍰",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/percentuali_001.jpg"
    },
    {
        "title": "Laboratorio di operazioni tra Frazioni",
        "excerpt": "Simulatore interattivo per comprendere le operazioni tra frazioni (Somma, Prodotto, Potenza) attraverso modelli visivi (Torte) e retta numerica.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "ARITMETICA",
            "EU:STEM",
            "FRAZIONI",
            "LAB",
            "MAT:CALCOLO",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "NUMERI RAZIONALI"
        ],
        "date": "2025-12-08",
        "url": "content/apps/fractions_lab_001.html",
        "type": "app",
        "icon": "🍰",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/fractions_lab_001.jpg"
    },
    {
        "title": "Guida 3D: Scomposizione di Polinomi (Algebra Tiles)",
        "excerpt": "Laboratorio interattivo 2D/3D per visualizzare la fattorizzazione di polinomi come aree e volumi. Include esportazione STL per la stampa 3D dei kit didattici.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "ALGEBRA",
            "EU:STEM",
            "GEOMETRIA",
            "IND:STRUMENTAZIONE",
            "LAB",
            "MAT:GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "POLINOMI",
            "STAMPA 3D"
        ],
        "date": "2025-12-08",
        "url": "content/apps/visualizzatore polinomi 2d 3d 001.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/visualizzatore polinomi 2d 3d 001.jpg"
    },
    {
        "title": "GonioMatch: Memory su valori notevoli di funzioni goniometriche",
        "excerpt": "Arcade educativo per allenare il riconoscimento immediato dei valori trigonometrici (Seno, Coseno) sulla circonferenza goniometrica.",
        "tags": [
            "3 MEC",
            "4 EL",
            "ANGOLI",
            "FUNZIONI",
            "GAMIFICATION",
            "GONIOMETRIA",
            "LAB",
            "MAT:ANALISI",
            "MATEMATICA",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE",
            "TRIGONOMETRIA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/gioco_sin_cos_01.html",
        "type": "app",
        "icon": "📈",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/gioco_sin_cos_01.jpg"
    },
    {
        "title": "Albero di Pitagora: Frattali 3D",
        "excerpt": "Simulazione WebGL dell'Albero di Pitagora in 3D. Un'esplorazione visiva dei frattali e delle relazioni geometriche tra i quadrati.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "3 MEC",
            "ALGORITMI",
            "CODING",
            "EU:STEM",
            "FRATTALI",
            "GEOMETRIA",
            "LAB",
            "MAT:GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "MAT_A4:APPLICARE PROPRIETÀ GEOMETRICHE IN CONTESTI OPERATIVI",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "PITAGORA",
            "RICORSIONE",
            "STAMPA 3D"
        ],
        "date": "2025-12-08",
        "url": "content/apps/albero_pitagorico_3d_gemini_001.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/albero_pitagorico_3d_gemini_001.jpg"
    },
    {
        "title": "AlgebraLab 3D: Scomposizione di polinomi attraverso prodotti notevoli e trinomio speciale",
        "excerpt": "Simulatore 3D interattivo per visualizzare prodotti notevoli e scomposizioni come aree e volumi.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "3 MEC",
            "4 EL",
            "ALGEBRA",
            "EU:STEM",
            "GEOMETRIA",
            "LAB",
            "MAT:GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "VISUALIZZAZIONE"
        ],
        "date": "2025-12-08",
        "url": "content/apps/scomp_3d_grafica_002.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/scomp_3d_grafica_002.jpg"
    },
    {
        "title": "Parabola Challenge: Disequazioni",
        "excerpt": "Videogioco didattico a livelli sulle disequazioni di secondo grado. Scaffolding progressivo fino all'input testuale libero.",
        "tags": [
            "3 MEC",
            "4 EL",
            "ALGEBRA",
            "DISEQUAZIONI",
            "GAMIFICATION",
            "MAT:ANALISI",
            "MAT:PROBLEMSOLVING",
            "MATEMATICA",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "MAT_K1:INSIEMI NUMERICI E CALCOLO LETTERALE",
            "PARABOLA",
            "SCAFFOLDING"
        ],
        "date": "2025-12-08",
        "url": "content/apps/disequazioni grafiche 4el.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/disequazioni grafiche 4el.jpg"
    },
    {
        "title": "Simulazione CA: Fasori & Onde",
        "excerpt": "Simulatore interattivo del comportamento in Corrente Alternata (Sfasamento, Valori Efficaci, Potenza) per il corso di macchine elettriche.",
        "tags": [
            "4 EL",
            "CORRENTE ALTERNATA",
            "ELETTROTECNICA",
            "FASORI",
            "FISICA",
            "IND:STRUMENTAZIONE",
            "LAB",
            "MAT:ANALISI",
            "MAT:MODELLIZZAZIONE",
            "ONDE"
        ],
        "date": "2025-12-08",
        "url": "content/apps/corrente_4el_sincos.html",
        "type": "app",
        "icon": "⚡",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/corrente_4el_sincos.jpg"
    },
    {
        "title": "Esploratore Numerico: Pitagora & Tartaglia",
        "excerpt": "Laboratorio interattivo per scoprire i pattern dei numeri: Tavola Pitagorica (Primi, Quadrati), Triangolo di Tartaglia (Combinatoria) e regole di divisibilità.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "4 EL",
            "ARITMETICA",
            "DIVISIBILITÀ",
            "LAB",
            "MAT:CALCOLO",
            "MAT:DATI",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "MAT_A4:APPLICARE PROPRIETÀ GEOMETRICHE IN CONTESTI OPERATIVI",
            "MAT_C3:ANALIZZARE DATI E INTERPRETARE INFORMAZIONI CON STRUMENTI STATISTICI E PROBABILISTICI",
            "NUMERI",
            "PITAGORA",
            "TARTAGLIA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/tavola_tart_canva0003.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/tavola_tart_canva0003.jpg"
    },
    {
        "title": "Sketch to Pattern: Arte Generativa",
        "excerpt": "Strumento di arte generativa che trasforma schizzi a mano libera in pattern geometrici complessi. Sperimenta con algoritmi, semplificazione e tassellazioni.",
        "tags": [
            "ARTE",
            "CIT_4:COMPETENZA DIGITALE",
            "CODING",
            "CREATIVITÀ",
            "EU:CULTURALE",
            "EU:DIGITALE",
            "GEOMETRIA",
            "LAB",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "PATTERN",
            "TECNOLOGIA",
            "TINKERING"
        ],
        "date": "2025-12-08",
        "url": "content/apps/sketch_to_pattern_gemini_005.html",
        "type": "app",
        "icon": "📐",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/sketch_to_pattern_gemini_005.jpg"
    },
    {
        "title": "Logic Lab: Insiemi & Venn",
        "excerpt": "Laboratorio interattivo per esplorare la Teoria degli Insiemi. Definisci gli elementi, componi espressioni logiche (Unione, Intersezione) e visualizza i Diagrammi di Venn in tempo reale.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "DIAGRAMMI DI VENN",
            "EU:STEM",
            "INSIEMI",
            "LAB",
            "LOGICA",
            "MAT:LOGICA",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "MAT_C2:UTILIZZARE STRATEGIE DEL PENSIERO RAZIONALE PER AFFRONTARE SITUAZIONI PROBLEMATICHE IN CONTESTI REALI"
        ],
        "date": "2025-12-08",
        "url": "content/apps/insiemi004.html",
        "type": "app",
        "icon": "🔴",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/insiemi004.jpg"
    },
    {
        "title": "Mappe & Distorsioni: Mercatore",
        "excerpt": "Modello interattivo in D3.js per esplorare le distorsioni della proiezione di Mercatore confrontando le aree reali dei paesi.",
        "tags": [
            "1 EL",
            "2 EL",
            "2 GP",
            "COORDINATE",
            "EU:STEM",
            "GEOGRAFIA",
            "LAB",
            "MAT:GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "MAT_K3:GEOMETRIA EUCLIDEA E ANALITICA",
            "MERCATORE",
            "PROIEZIONI",
            "SCALA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/mercatore_correzione_001_gemini_worksproperly.html",
        "type": "app",
        "icon": "🌍",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/mercatore_correzione_001_gemini_worksproperly.jpg"
    },
    {
        "title": "Math Underground: Mappa per la classificazione di Funzioni",
        "excerpt": "Mappa interattiva della metropolitana per lo studio teorico delle funzioni analitiche e delle loro principali proprietà (Dominio, Codominio).",
        "tags": [
            "4 EL",
            "ANALISI",
            "DOMINIO",
            "EU:STEM",
            "FUNZIONI",
            "LAB",
            "MAPPA",
            "MAT:ANALISI",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "MAT_A2:RAPPRESENTARE DATI MEDIANTE TABELLE, GRAFICI E FUNZIONI",
            "MAT_K2:FUNZIONI ELEMENTARI E LORO RAPPRESENTAZIONE"
        ],
        "date": "2025-12-06",
        "url": "content/apps/math_underground003_4el.html",
        "type": "app",
        "icon": "📈",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/math_underground003_4el.jpg"
    },
    {
        "title": "Math Invaders",
        "excerpt": "Laboratorio procedurale per il calcolo del Massimo Comune Divisore e Minimo Comune Multiplo tramite scomposizione in fattori primi.",
        "tags": [
            "1 EL",
            "ARITMETICA",
            "GAMIFICATION",
            "MAT:CALCOLO",
            "MATEMATICA",
            "MCD",
            "MCM",
            "VIDEOGIOCO"
        ],
        "date": "2025-12-02",
        "url": "content/apps/MCD_mcm_1el_001.html",
        "type": "app",
        "icon": "🔢",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/MCD_mcm_1el_001.jpg"
    },
    {
        "title": "Chaos Lab: Sistemi Dinamici",
        "excerpt": "Simulatore 3D di Attrattori Strani (Lorenz, Rössler, Chen). Esplora il Caos Deterministico e le Equazioni Differenziali tramite integrazione numerica RK4.",
        "tags": [
            "2 EL",
            "2 GP",
            "4 EL",
            "ANALISI",
            "ATTRATTORI",
            "CAOS",
            "CIT_4:COMPETENZA DIGITALE",
            "EU:DIGITALE",
            "EU:STEM",
            "FISICA",
            "MAT:ANALISI",
            "MAT:MODELLIZZAZIONE",
            "MATEMATICA",
            "MAT_A3:RISOLVERE EQUAZIONI, DISEQUAZIONI E SISTEMI",
            "SIMULAZIONE",
            "SISTEMI DINAMICI"
        ],
        "date": "2025-10-24",
        "url": "content/apps/attrattori_001_dec25.html",
        "type": "app",
        "icon": "📈",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/attrattori_001_dec25.jpg"
    },
    {
        "title": "Caccia all'Errore: Memory su Operazioni in Z",
        "excerpt": "Missione di addestramento sui Numeri Interi (Z) e le Potenze. Trova le corrispondenze corrette ed evita le trappole degli errori comuni di calcolo.",
        "tags": [
            "1 EL",
            "ARITMETICA",
            "ERRORI COMUNI",
            "EU:STEM",
            "GAMIFICATION",
            "MAT:CALCOLO",
            "MAT:PROBLEMSOLVING",
            "MATEMATICA",
            "NUMERI INTERI",
            "POTENZE",
            "Z"
        ],
        "date": "2025-10-20",
        "url": "content/apps/memory_1el_numeri_004.html",
        "type": "app",
        "icon": "🔢",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/memory_1el_numeri_004.jpg"
    }
];