/* 
   ⚠️ GENERATO AUTOMATICAMENTE DA build.py 
   Data: 2026-04-27 18:19:57
*/

module.exports = [
    {
        "title": "Polinomi Challenge 3D PRO",
        "excerpt": "Versione PRO della sfida 3D sui polinomi: Ghost Target, X-Ray mode e variabili dinamiche.",
        "tags": [
            "POLINOMI",
            "3D",
            "PRO",
            "MATEMATICA",
            "1 EL",
            "NERDAMER",
            "ALGEBRA",
            "SCOMPOSIZIONE"
        ],
        "date": "2026-05-27",
        "url": "content/apps/polinomi_challenge_v2_pro.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/polinomi_challenge_v2_pro.jpg"
    },
    {
        "title": "Scomposizione Polinomi",
        "excerpt": "Gioco Memory per allenare il riconoscimento dei prodotti notevoli e delle scomposizioni (Raccoglimento, Quadrati, Trinomi).",
        "tags": [
            "POLINOMI",
            "EU:IMPARAREIMPARARE",
            "2 EL",
            "SCOMPOSIZIONI",
            "MAT:CALCOLO",
            "GAMIFICATION",
            "PRODOTTI NOTEVOLI",
            "MATEMATICA",
            "1 EL",
            "2 GP",
            "ALGEBRA"
        ],
        "date": "2026-04-24",
        "url": "content/apps/cards_polinomi_memory004.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/cards_polinomi_memory004.jpg"
    },
    {
        "title": "C.E. Match",
        "excerpt": "Gioco Memory sul riconoscimento delle condizioni di esistenza di frazioni algebriche.",
        "tags": [
            "POLINOMI",
            "EU:IMPARAREIMPARARE",
            "2 EL",
            "SCOMPOSIZIONI",
            "MAT:CALCOLO",
            "GAMIFICATION",
            "PRODOTTI NOTEVOLI",
            "MATEMATICA",
            "1 EL",
            "2 GP",
            "ALGEBRA"
        ],
        "date": "2026-04-24",
        "url": "content/apps/card_frazioni_algebriche_005.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "memory",
        "thumbnail": "content/assets/thumbnails/card_frazioni_algebriche_005.jpg"
    },
    {
        "title": "Game Theory Lab 2.5 🎲",
        "excerpt": "Simulazione interattiva del Dilemma del Prigioniero ed Equilibrio di Nash. Laboratorio per esplorare la cooperazione e le scelte strategiche nel contesto del voto scolastico.",
        "tags": [
            "CIV:COSTITUZIONE",
            "CITTADINANZA",
            "4 EL",
            "TEORIA DEI GIOCHI",
            "MATEMATICA",
            "MAT:DATI",
            "MAT_C3:ANALIZZARE DATI E INTERPRETARE INFORMAZIONI C...",
            "EQUILIBRIO DI NASH",
            "ED. CIVICA",
            "MAT:MODELLIZZAZIONE",
            "EU:CITTADINANZA"
        ],
        "date": "2026-04-24",
        "url": "content/apps/voto_cosapevole.2.5.html",
        "type": "app",
        "icon": "🎮",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/voto_cosapevole.2.5.jpg"
    },
    {
        "title": "PixelGrid",
        "excerpt": "Applicazione di Game Theory all'analisi delle radici nelle equazioni di secondo grado, esplorando l'ottimizzazione e le strategie dominanti.",
        "tags": [
            "ITA",
            "G",
            "3 MEC",
            "POLINOMI",
            "PARABOLA",
            "4 EL",
            "EQUAZIONI DI SECONDO GRADO",
            "PRODOTTI NOTEVOLI",
            "FATTORIZZAZIONE",
            "QUADRATICHE",
            "MODELLIZZAZIONE",
            "ALGEBRA",
            "SCOMPOSIZIONE"
        ],
        "date": "2026-04-24",
        "url": "content/apps/eq_2_gr_teoria_giochi_01.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/eq_2_gr_teoria_giochi_01.jpg"
    },
    {
        "title": "Hyperchaos Fractal Engine 3D",
        "excerpt": "Simulatore frattale 3D interattivo. Generatore algoritmico con geometria variabile, passeggiate aleatorie (Random Walk) e memoria cromatica nello spazio.",
        "tags": [
            "GEOMETRIA",
            "CAOS",
            "MAT_K03:GEOMETRIA EUCLIDEA E ANALITICA",
            "ALGORITMI",
            "FRATTALI",
            "3D",
            "RANDOM WALK",
            "WEBGL",
            "SIMULATORE"
        ],
        "date": "2026-04-23",
        "url": "content/apps/random_walk.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/random_walk.jpg"
    },
    {
        "title": "Lissajous Curves 3D",
        "excerpt": "Esplorazione interattiva delle curve di Lissajous in 2D e 3D. Simulatore matematico con morphing sferico e decadimento visivo.",
        "tags": [
            "GEOMETRIA",
            "ONDE",
            "DIDATTICA",
            "FISICA",
            "3D",
            "OSCILLAZIONI",
            "MATEMATICA",
            "LISSAJOUS",
            "WEBGL",
            "LABORATORIO"
        ],
        "date": "2026-04-21",
        "url": "content/apps/lissajous_curves_01.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/lissajous_curves_01.jpg"
    },
    {
        "title": "$\\pi$ is irrational",
        "excerpt": "Simulatore ultra-high res. della costante $\\pi$. Esplorazione dell'incommensurabilità con morfing sferico e shader glow.",
        "tags": [
            "GEOMETRIA",
            "ROTAZIONE",
            "SHADER",
            "$\\PI$",
            "PI GRECO",
            "3D",
            "INCOMMENSURABILITÀ",
            "MATEMATICA",
            "WEBGL",
            "GLOW"
        ],
        "date": "2026-04-21",
        "url": "content/apps/pi_is_irrational.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/pi_is_irrational.jpg"
    },
    {
        "title": "$\\sqrt{2}$ is irrational",
        "excerpt": "Simulatore sferico dell'Albero di Pitagora. Algoritmo di Soft Fusion per eliminare artefatti di complanarità e mostrare l'irrazionalità di $\\sqrt{2}$.",
        "tags": [
            "GEOMETRIA",
            "$\\SQRT{2}$",
            "SQRT(2)",
            "FRATTALI",
            "3D",
            "MATEMATICA",
            "SOFT FUSION",
            "WEBGL",
            "INCOMMENSURABILITÀ",
            "ALBERO PITAGORICO"
        ],
        "date": "2026-04-21",
        "url": "content/apps/sqrt2_is_irrational.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/sqrt2_is_irrational.jpg"
    },
    {
        "title": "Allegato Dlgs (Parte 61) 2017",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Allegato, Dlgs61, Funzion..",
        "tags": [
            "3 MEC",
            "LIMITE",
            "DLGS61",
            "ALLEGATO",
            "INSIEM",
            "RETTA",
            "FUNZION"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_dlgs61",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/Allegato-A_dlgs61_2017.pdf",
        "type": "normativa",
        "icon": "🧩",
        "game_type": "sim"
    },
    {
        "title": "Dlgs (Parte 61) 2017",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Dlgs, Funzion, Limite..",
        "tags": [
            "3 MEC",
            "LIMITE",
            "INSIEM",
            "STATISTICA",
            "ELETTRIC",
            "RETTA",
            "FUNZION",
            "DLGS"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_elettric",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/dlgs-61-2017.pdf",
        "type": "normativa",
        "icon": "📊",
        "game_type": "sim"
    },
    {
        "title": "Allegato (Parte 1) Competenze Pecup Professionali Area Generale Def (Parte 1)",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Allegato, Competenze, Pecup..",
        "tags": [
            "GEOMETRIA",
            "PROBABILITÀ",
            "3 MEC",
            "TRIGONOMETRIA",
            "EQUAZIONI",
            "DISEQUAZIONI",
            "POLINOM",
            "SCOMPOSIZION",
            "GRAFICO",
            "RETTA",
            "FUNZION",
            "INSIEM",
            "ALLEGATO",
            "STATISTICA",
            "PECUP",
            "PITAGORA",
            "COMPETENZE"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_competenze",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/ALLEGATO-1_-Competenze-pecup-professionali-area-generale-Def-1.pdf",
        "type": "normativa",
        "icon": "📈",
        "game_type": "sim"
    },
    {
        "title": "Linee Guida Parte Prima Seconda",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Linee, Guida, Parte..",
        "tags": [
            "LINEE",
            "3 MEC",
            "PARTE",
            "LIMITE",
            "INSIEM",
            "STATISTICA",
            "RETTA",
            "FUNZION",
            "GUIDA"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_parte",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/Linee-guida_PARTE-PRIMA-e-SECONDA.pdf",
        "type": "normativa",
        "icon": "📊",
        "game_type": "sim"
    },
    {
        "title": "Decreto Legislativo (Parte 13) (Parte 4) 2017 (Parte 61)",
        "excerpt": "Laboratorio interattivo. Punto focale sulle tematiche di: Decreto, Legislativo, Funzion..",
        "tags": [
            "3 MEC",
            "LEGISLATIVO",
            "LIMITE",
            "INSIEM",
            "STATISTICA",
            "RETTA",
            "FUNZION",
            "DECRETO"
        ],
        "date": "2026-04-19",
        "group_ref": "3_mec_2026-04-19_retta",
        "version_label": "Versione Unica",
        "url": "rif_norm_2017/decreto-legislativo-13-04-2017-n-61.pdf",
        "type": "normativa",
        "icon": "📊",
        "game_type": "sim"
    },
    {
        "title": "$\\phi$ is irrational",
        "excerpt": "Esplorazione interattiva 2D/3D del modulo aureo ($\\phi$). Simulatore WebGL per dimostrare l'incommensurabilità attraverso le proiezioni concentriche della spirale.",
        "tags": [
            "GEOMETRIA",
            "SPIRALE",
            "FRATTALI",
            "3D",
            "MATEMATICA",
            "WEBGL",
            "INCOMMENSURABILITÀ",
            "$\\PHI$"
        ],
        "date": "2026-04-03",
        "url": "content/apps/phi_is_irrational_01.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/phi_is_irrational_01.jpg"
    },
    {
        "title": "Il metodo di esaustione",
        "excerpt": "Visualizzazione parametrica del limite delle aree di poligoni regolari al crescere del numero dei lati per approssimare l'area del cerchio.",
        "tags": [
            "GEOMETRIA",
            "POLIGONI",
            "AREA",
            "PI GRECO",
            "LIMITI",
            "MATEMATICA",
            "ESAUSTIONE",
            "P5JS",
            "ARCHIMEDE"
        ],
        "date": "2026-04-03",
        "url": "content/apps/esaustione_01.html",
        "type": "app",
        "icon": "📈",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/esaustione_01.jpg"
    },
    {
        "title": "Esploratore Polinomiale",
        "excerpt": "Esploratore grafico per polinomi che permette di visualizzare l'effetto delle operazioni (Addizione, Sottrazione) sulle funzioni risultanti.",
        "tags": [
            "POLINOMI",
            "3 MEC",
            "EQUAZIONI FRAZIONARIE",
            "2 EL",
            "4 EL",
            "GRAFICO",
            "1 EL",
            "FUNZIONI FRAZIONARIE",
            "2 GP",
            "ALGEBRA",
            "SCOMPOSIZIONE"
        ],
        "date": "2026-04-02",
        "url": "content/apps/operazioni_polinomi_graph.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/operazioni_polinomi_graph.jpg"
    },
    {
        "title": "Sistemi di disequazioni vs disequazioni frazionarie",
        "excerpt": "Risolutore simbolico e interattivo per disequazioni frazionarie e sistemi matematici. Integra un tutor socratico passo passo per l'apprendimento guidato.",
        "tags": [
            "3 MEC",
            "2 EL",
            "FRAZIONARIE",
            "DISEQUAZIONI",
            "4 EL",
            "LOGICA",
            "MAT_C2:UTILIZZARE STRATEGIE DEL PENSIERO RAZIONALE P...",
            "TUTOR",
            "SISTEMI",
            "1 EL",
            "RISOLUTORE",
            "2 GP",
            "ALGEBRA"
        ],
        "date": "2026-04-02",
        "url": "content/apps/disequazioni_frazionarie_vs_sistemi.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/disequazioni_frazionarie_vs_sistemi.jpg"
    },
    {
        "title": "Decodifica Matematica",
        "excerpt": "Materiale didattico esplorativo relativo a: Decodifica Matematica..",
        "tags": [
            "DECODIFICA",
            "MATEMATICA"
        ],
        "date": "2025-12-15",
        "group_ref": "decodifica matematica",
        "version_label": "Versione Unica",
        "url": "content/infografiche/decodifica_la_matematica.pdf",
        "type": "infographic",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/decodifica_la_matematica.jpg"
    },
    {
        "title": "Errori Comuni (Parte 2)",
        "excerpt": "Materiale didattico esplorativo relativo a: Errori Comuni (Parte 2)..",
        "tags": [
            "COMUNI02",
            "ERRORI"
        ],
        "date": "2025-12-15",
        "group_ref": "errori comuni (parte 2)",
        "version_label": "Versione Unica",
        "url": "content/infografiche/errori_comuni02.png",
        "type": "infographic",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/errori_comuni02.jpg"
    },
    {
        "date": "2025-12-12",
        "description": "Applicazione intelligente sperimentale sviluppata con Google AI Studio. Offre supporto avanzato e analisi contestuale.",
        "tags": [
            "GOOGLE",
            "STRUMENTI",
            "GEMINI",
            "LINKOGRAFIA",
            "ASSISTANT",
            "AI"
        ],
        "title": "Google AI Studio: Assistant",
        "url": "https://ais-pre-evi2uqxownrirtwtzubadt-238287108414.europe-west2.run.app/",
        "excerpt": "Applicazione intelligente sperimentale sviluppata con Google AI Studio. Offre supporto avanzato e analisi contestuale.",
        "type": "link",
        "icon": "🌐",
        "game_type": "standard"
    },
    {
        "title": "Guida Mondo Delle Funzioni Matematiche",
        "excerpt": "Materiale didattico esplorativo relativo a: Guida Mondo Delle Funzioni Matematiche..",
        "tags": [
            "MONDO",
            "GUIDA",
            "DELLE"
        ],
        "date": "2025-12-12",
        "group_ref": "guida mondo delle funzioni matematiche",
        "version_label": "Versione Unica",
        "url": "content/infografiche/guida_al_mondo_delle_funzioni_matematiche.pdf",
        "type": "infographic",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/guida_al_mondo_delle_funzioni_matematiche.jpg"
    },
    {
        "title": "Tattoo Matematico Delta",
        "excerpt": "Materiale didattico esplorativo relativo a: Tattoo Matematico Delta..",
        "tags": [
            "TATTOO",
            "DELTA"
        ],
        "date": "2025-12-12",
        "group_ref": "tattoo matematico delta",
        "version_label": "Versione Unica",
        "url": "content/images/tattoo_delta.png",
        "type": "image",
        "icon": "🖼️",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/tattoo_delta.jpg"
    },
    {
        "title": "PIP",
        "excerpt": "Terminale didattico Orfini Industries. Simulatore open source per lo studio della retta (y=mx+q).",
        "tags": [
            "3 MEC",
            "2 PUNTI",
            "PENDENZA",
            "4 EL",
            "RETTA",
            "GAMIFICATION",
            "FALLOUT",
            "MATEMATICA",
            "GEOMETRIA ANALITICA"
        ],
        "date": "2025-12-12",
        "url": "content/apps/retta_fallout_002.html",
        "type": "app",
        "icon": "📐",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/retta_fallout_002.jpg"
    },
    {
        "title": "Percent Lab",
        "excerpt": "Laboratorio interattivo sulle percentuali. Visualizzazione, calcolo mentale e gamification.",
        "tags": [
            "PERCENTUALI",
            "ARITMETICA",
            "CALCOLO MENTALE",
            "GAMIFICATION",
            "MATEMATICA",
            "1 EL"
        ],
        "date": "2025-12-10",
        "url": "content/apps/percentuali_001.html",
        "type": "app",
        "icon": "🍰",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/percentuali_001.jpg"
    },
    {
        "title": "Studio di Funzioni: Lab Analisi + AI",
        "excerpt": "Suite completa per lo studio di funzioni reali: dominio, simmetrie, classificazione e composizione. Grafici interattivi e analisi in tempo reale powered by Gemini.",
        "tags": [
            "FUNZIONI",
            "STUDIO DI FUNZIONE",
            "ANALISI",
            "EDUCATION",
            "GEMINI",
            "DOMINIO",
            "GRAFICI",
            "MATEMATICA",
            "AI"
        ],
        "date": "2025-12-10",
        "url": "content/apps/functions_lab_008.html",
        "type": "app",
        "icon": "📈",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/functions_lab_008.jpg"
    },
    {
        "title": "Laboratorio Frazioni: Operazioni Visive",
        "excerpt": "Simulatore interattivo per comprendere le operazioni tra frazioni (Somma, Prodotto, Potenza) attraverso modelli visivi (Torte) e retta numerica.",
        "tags": [
            "MAT:MODELLIZZAZIONE",
            "EU:STEM",
            "ARITMETICA",
            "NUMERI RAZIONALI",
            "2 EL",
            "MAT:CALCOLO",
            "LAB",
            "MATEMATICA",
            "1 EL",
            "2 GP",
            "FRAZIONI"
        ],
        "date": "2025-12-08",
        "url": "content/apps/fractions_lab_001.html",
        "type": "app",
        "icon": "🍰",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/fractions_lab_001.jpg"
    },
    {
        "title": "Algebra Tiles 3D: Scomposizione",
        "excerpt": "Laboratorio interattivo 2D/3D per visualizzare la fattorizzazione di polinomi come aree e volumi. Include esportazione STL per la stampa 3D dei kit didattici.",
        "tags": [
            "GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "POLINOMI",
            "EU:STEM",
            "STAMPA 3D",
            "2 EL",
            "LAB",
            "MATEMATICA",
            "IND:STRUMENTAZIONE",
            "2 GP",
            "1 EL",
            "MAT:GEOMETRIA",
            "ALGEBRA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/visualizzatore polinomi 2d 3d 001.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/visualizzatore polinomi 2d 3d 001.jpg"
    },
    {
        "title": "GonioMatch: Segnali Goniometrici",
        "excerpt": "Arcade educativo per allenare il riconoscimento immediato dei valori trigonometrici (Seno, Coseno) sulla circonferenza goniometrica.",
        "tags": [
            "FUNZIONI",
            "3 MEC",
            "ANGOLI",
            "TRIGONOMETRIA",
            "4 EL",
            "MAT:ANALISI",
            "LAB",
            "MATEMATICA",
            "GAMIFICATION",
            "GONIOMETRIA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/gioco_sin_cos_01.html",
        "type": "app",
        "icon": "📈",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/gioco_sin_cos_01.jpg"
    },
    {
        "title": "Albero di Pitagora: Frattali 3D",
        "excerpt": "Simulazione WebGL dell'Albero di Pitagora in 3D. Un'esplorazione visiva dei frattali e delle relazioni geometriche tra i quadrati.",
        "tags": [
            "GEOMETRIA",
            "RICORSIONE",
            "3 MEC",
            "EU:STEM",
            "CODING",
            "ALGORITMI",
            "STAMPA 3D",
            "2 EL",
            "FRATTALI",
            "LAB",
            "MATEMATICA",
            "2 GP",
            "1 EL",
            "PITAGORA",
            "MAT:GEOMETRIA",
            "MAT:MODELLIZZAZIONE"
        ],
        "date": "2025-12-08",
        "url": "content/apps/albero_pitagorico_3d_gemini_001.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/albero_pitagorico_3d_gemini_001.jpg"
    },
    {
        "title": "AlgebraLab 3D: Geometria dei Polinomi",
        "excerpt": "Simulatore 3D interattivo per visualizzare prodotti notevoli e scomposizioni come aree e volumi.",
        "tags": [
            "GEOMETRIA",
            "MAT:MODELLIZZAZIONE",
            "3 MEC",
            "EU:STEM",
            "VISUALIZZAZIONE",
            "2 EL",
            "4 EL",
            "LAB",
            "MATEMATICA",
            "2 GP",
            "1 EL",
            "MAT:GEOMETRIA",
            "ALGEBRA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/scomp_3d_grafica_002.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/scomp_3d_grafica_002.jpg"
    },
    {
        "title": "Parabola Challenge: Disequazioni",
        "excerpt": "Videogioco didattico a livelli sulle disequazioni di secondo grado. Scaffolding progressivo fino all'input testuale libero.",
        "tags": [
            "3 MEC",
            "MAT:PROBLEMSOLVING",
            "4 EL",
            "DISEQUAZIONI",
            "SCAFFOLDING",
            "MAT:ANALISI",
            "GAMIFICATION",
            "MATEMATICA",
            "ALGEBRA",
            "PARABOLA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/disequazioni grafiche 4el.html",
        "type": "app",
        "icon": "🧱",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/disequazioni grafiche 4el.jpg"
    },
    {
        "title": "Simulazione CA: Fasori & Onde",
        "excerpt": "Simulatore interattivo del comportamento in Corrente Alternata (Sfasamento, Valori Efficaci, Potenza) per il corso di macchine elettriche.",
        "tags": [
            "FASORI",
            "ELETTROTECNICA",
            "CORRENTE ALTERNATA",
            "ONDE",
            "4 EL",
            "FISICA",
            "MAT:ANALISI",
            "LAB",
            "IND:STRUMENTAZIONE",
            "MAT:MODELLIZZAZIONE"
        ],
        "date": "2025-12-08",
        "url": "content/apps/corrente_4el_sincos.html",
        "type": "app",
        "icon": "⚡",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/corrente_4el_sincos.jpg"
    },
    {
        "title": "Esploratore Numerico: Pitagora & Tartaglia",
        "excerpt": "Laboratorio interattivo per scoprire i pattern dei numeri: Tavola Pitagorica (Primi, Quadrati), Triangolo di Tartaglia (Combinatoria) e regole di divisibilità.",
        "tags": [
            "TARTAGLIA",
            "ARITMETICA",
            "NUMERI",
            "2 EL",
            "4 EL",
            "DIVISIBILITÀ",
            "MAT:CALCOLO",
            "LAB",
            "MATEMATICA",
            "MAT:DATI",
            "MAT_C3:ANALIZZARE DATI E INTERPRETARE INFORMAZIONI C...",
            "1 EL",
            "PITAGORA",
            "2 GP",
            "MAT:MODELLIZZAZIONE"
        ],
        "date": "2025-12-08",
        "url": "content/apps/tavola_tart_canva0003.html",
        "type": "app",
        "icon": "📐",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/tavola_tart_canva0003.jpg"
    },
    {
        "title": "Sketch to Pattern: Arte Generativa",
        "excerpt": "Strumento di arte generativa che trasforma schizzi a mano libera in pattern geometrici complessi. Sperimenta con algoritmi, semplificazione e tassellazioni.",
        "tags": [
            "GEOMETRIA",
            "PATTERN",
            "CODING",
            "EU:CULTURALE",
            "ARTE",
            "TINKERING",
            "LAB",
            "EU:DIGITALE",
            "CREATIVITÀ",
            "TECNOLOGIA"
        ],
        "date": "2025-12-08",
        "url": "content/apps/sketch_to_pattern_gemini_005.html",
        "type": "app",
        "icon": "📐",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/sketch_to_pattern_gemini_005.jpg"
    },
    {
        "title": "Logic Lab: Insiemi & Venn",
        "excerpt": "Laboratorio interattivo per esplorare la Teoria degli Insiemi. Definisci gli elementi, componi espressioni logiche (Unione, Intersezione) e visualizza i Diagrammi di Venn in tempo reale.",
        "tags": [
            "EU:STEM",
            "DIAGRAMMI DI VENN",
            "2 EL",
            "INSIEMI",
            "LOGICA",
            "MAT:LOGICA",
            "MAT_C2:UTILIZZARE STRATEGIE DEL PENSIERO RAZIONALE P...",
            "LAB",
            "MATEMATICA",
            "1 EL",
            "2 GP",
            "MAT:MODELLIZZAZIONE"
        ],
        "date": "2025-12-08",
        "url": "content/apps/insiemi004.html",
        "type": "app",
        "icon": "🔴",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/insiemi004.jpg"
    },
    {
        "title": "Mappe & Distorsioni: Mercatore",
        "excerpt": "Modello interattivo in D3.js per esplorare le distorsioni della proiezione di Mercatore confrontando le aree reali dei paesi.",
        "tags": [
            "EU:STEM",
            "PROIEZIONI",
            "2 EL",
            "COORDINATE",
            "SCALA",
            "MERCATORE",
            "LAB",
            "MATEMATICA",
            "2 GP",
            "1 EL",
            "MAT:GEOMETRIA",
            "GEOGRAFIA",
            "MAT:MODELLIZZAZIONE"
        ],
        "date": "2025-12-08",
        "url": "content/apps/mercatore_correzione_001_gemini_worksproperly.html",
        "type": "app",
        "icon": "🌍",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/mercatore_correzione_001_gemini_worksproperly.jpg"
    },
    {
        "title": "Math Underground: Mappa Funzioni",
        "excerpt": "Mappa interattiva della metropolitana per lo studio teorico delle funzioni analitiche e delle loro principali proprietà (Dominio, Codominio).",
        "tags": [
            "FUNZIONI",
            "EU:STEM",
            "ANALISI",
            "4 EL",
            "DOMINIO",
            "MAT:ANALISI",
            "LAB",
            "MATEMATICA",
            "MAPPA",
            "MAT:MODELLIZZAZIONE"
        ],
        "date": "2025-12-06",
        "url": "content/apps/math_underground003_4el.html",
        "type": "app",
        "icon": "📈",
        "game_type": "standard",
        "thumbnail": "content/assets/thumbnails/math_underground003_4el.jpg"
    },
    {
        "title": "Math Invaders",
        "excerpt": "Laboratorio procedurale per il calcolo del Massimo Comune Divisore e Minimo Comune Multiplo tramite scomposizione in fattori primi.",
        "tags": [
            "MCD",
            "MCM",
            "ARITMETICA",
            "MAT:CALCOLO",
            "GAMIFICATION",
            "MATEMATICA",
            "VIDEOGIOCO",
            "1 EL"
        ],
        "date": "2025-12-02",
        "url": "content/apps/MCD_mcm_1el_001.html",
        "type": "app",
        "icon": "🔢",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/MCD_mcm_1el_001.jpg"
    },
    {
        "title": "Chaos Lab: Sistemi Dinamici",
        "excerpt": "Simulatore 3D di Attrattori Strani (Lorenz, Rössler, Chen). Esplora il Caos Deterministico e le Equazioni Differenziali tramite integrazione numerica RK4.",
        "tags": [
            "CAOS",
            "EU:STEM",
            "ANALISI",
            "2 EL",
            "4 EL",
            "FISICA",
            "ATTRATTORI",
            "SISTEMI DINAMICI",
            "MAT:ANALISI",
            "MATEMATICA",
            "SIMULAZIONE",
            "EU:DIGITALE",
            "2 GP",
            "MAT:MODELLIZZAZIONE"
        ],
        "date": "2025-10-24",
        "url": "content/apps/attrattori_001_dec25.html",
        "type": "app",
        "icon": "📈",
        "game_type": "sim",
        "thumbnail": "content/assets/thumbnails/attrattori_001_dec25.jpg"
    },
    {
        "title": "Caccia all'Errore: Operazioni in Z",
        "excerpt": "Missione di addestramento sui Numeri Interi (Z) e le Potenze. Trova le corrispondenze corrette ed evita le trappole degli errori comuni di calcolo.",
        "tags": [
            "EU:STEM",
            "ARITMETICA",
            "MAT:PROBLEMSOLVING",
            "MAT:CALCOLO",
            "NUMERI INTERI",
            "GAMIFICATION",
            "MATEMATICA",
            "POTENZE",
            "ERRORI COMUNI",
            "Z",
            "1 EL"
        ],
        "date": "2025-10-20",
        "url": "content/apps/memory_1el_numeri_004.html",
        "type": "app",
        "icon": "🔢",
        "game_type": "arcade",
        "thumbnail": "content/assets/thumbnails/memory_1el_numeri_004.jpg"
    }
]